"""fenologia_por_talhao_grupos

Revision ID: 007c96c4009a
Revises: 7dc0dc31315d
Create Date: 2026-03-27 15:30:51.242082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007c96c4009a'
down_revision: Union[str, Sequence[str], None] = '7dc0dc31315d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
