"""add_fin_notas_fiscais

Revision ID: 0128896cd826
Revises: 02799c7f2478
Create Date: 2026-04-04 15:04:02.444970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0128896cd826'
down_revision: Union[str, Sequence[str], None] = '02799c7f2478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fin_notas_fiscais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.Enum('NFP_E', 'NF_E', 'NFC_E', name='tiponf'), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('emitente_nome', sa.String(length=200), nullable=False),
    sa.Column('emitente_cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('destinatario_nome', sa.String(length=200), nullable=False),
    sa.Column('destinatario_documento', sa.String(length=18), nullable=True),
    sa.Column('destinatario_uf', sa.String(length=2), nullable=True),
    sa.Column('valor_produtos', sa.Float(), nullable=False),
    sa.Column('valor_frete', sa.Float(), nullable=False),
    sa.Column('valor_icms', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('status_sefaz', sa.Enum('EM_DIGITACAO', 'ASSINADA', 'TRANSMITIDA', 'AUTORIZADA', 'CANCELADA', 'DENEGADA', 'INUTILIZADA', name='statussefaz'), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('numero_protocolo', sa.String(length=50), nullable=True),
    sa.Column('numero_recibo', sa.String(length=50), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.Column('descricao_produto', sa.String(length=300), nullable=True),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=6), nullable=True),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_autorizacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_cancelamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fin_notas_fiscais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fin_notas_fiscais_chave_acesso'), ['chave_acesso'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_notas_fiscais_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fin_notas_fiscais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_notas_fiscais_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_fin_notas_fiscais_chave_acesso'))

    op.drop_table('fin_notas_fiscais')
    # ### end Alembic commands ###
