"""add_rh_esocial_eventos

Revision ID: 02799c7f2478
Revises: 60cf3fe20cfc
Create Date: 2026-04-04 14:58:38.973822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02799c7f2478'
down_revision: Union[str, Sequence[str], None] = '60cf3fe20cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rh_esocial_eventos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('colaborador_id', sa.Uuid(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=10), nullable=False, comment='S-2200 | S-2300 | S-2299 | S-1200 | S-2400'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PENDENTE | ENVIADO | ERRO | PROCESSANDO'),
    sa.Column('numero_recibo', sa.String(length=50), nullable=True),
    sa.Column('codigo_erro', sa.String(length=20), nullable=True),
    sa.Column('descricao_erro', sa.Text(), nullable=True),
    sa.Column('colaborador_nome', sa.String(length=200), nullable=True),
    sa.Column('periodo_apuracao', sa.String(length=7), nullable=True, comment='YYYY-MM'),
    sa.Column('xml_enviado', sa.Text(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['rh_colaboradores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rh_esocial_eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rh_esocial_eventos_colaborador_id'), ['colaborador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rh_esocial_eventos_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('rh_esocial_eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rh_esocial_eventos_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_rh_esocial_eventos_colaborador_id'))

    op.drop_table('rh_esocial_eventos')
    # ### end Alembic commands ###
