"""add_insumo_operacao_fk_estoque_produto

Revision ID: 02e5c1fef995
Revises: c28e38e960aa
Create Date: 2026-03-22 23:35:37.553014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e5c1fef995'
down_revision: Union[str, Sequence[str], None] = 'c28e38e960aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos_operacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insumos_operacao_insumo_id'), ['insumo_id'], unique=False)
        batch_op.create_foreign_key(None, 'estoque_produtos', ['insumo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insumos_operacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_insumos_operacao_insumo_id'))

    # ### end Alembic commands ###
