"""cadastros_equipamentos_propriedades_commodities

Revision ID: 06d9e4c7ed54
Revises: 556b7b957de3
Create Date: 2026-03-25 01:02:48.151934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d9e4c7ed54'
down_revision: Union[str, Sequence[str], None] = '556b7b957de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
