"""marcas_modelos_categorias_sistema_nullable

Revision ID: 08262413a4e2
Revises: ab2e515b14fe
Create Date: 2026-03-26 03:27:44.457187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08262413a4e2'
down_revision: Union[str, Sequence[str], None] = 'ab2e515b14fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_tenant_id'))

    op.drop_table('notificacoes')
    with op.batch_alter_table('cadastros_categorias_produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema', sa.Boolean(), nullable=False, comment='True = não editável pelo tenant'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='NULL = padrão do sistema')

    with op.batch_alter_table('cadastros_marcas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema', sa.Boolean(), nullable=False, comment='True = não editável pelo tenant'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='NULL = padrão do sistema')

    with op.batch_alter_table('cadastros_modelos_produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema', sa.Boolean(), nullable=False, comment='True = não editável pelo tenant'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='NULL = padrão do sistema')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_modelos_produto', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='NULL = padrão do sistema')
        batch_op.drop_column('sistema')

    with op.batch_alter_table('cadastros_marcas', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='NULL = padrão do sistema')
        batch_op.drop_column('sistema')

    with op.batch_alter_table('cadastros_categorias_produto', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='NULL = padrão do sistema')
        batch_op.drop_column('sistema')

    op.create_table('notificacoes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('mensagem', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('lida', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('notificacoes_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notificacoes_pkey'))
    )
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###
