"""checklist_agricola

Revision ID: 08c865830c43
Revises: 4b6b337b818f
Create Date: 2026-03-27 16:51:51.474472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c865830c43'
down_revision: Union[str, Sequence[str], None] = '4b6b337b818f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('cultura', sa.String(length=50), nullable=True),
    sa.Column('fase', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_templates_cultura'), ['cultura'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_templates_fase'), ['fase'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('safra_checklist_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('fase', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safra_checklist_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safra_checklist_itens_fase'), ['fase'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_checklist_itens_safra_id'), ['safra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_checklist_itens_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safra_checklist_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safra_checklist_itens_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_safra_checklist_itens_safra_id'))
        batch_op.drop_index(batch_op.f('ix_safra_checklist_itens_fase'))

    op.drop_table('safra_checklist_itens')
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_templates_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_templates_fase'))
        batch_op.drop_index(batch_op.f('ix_checklist_templates_cultura'))

    op.drop_table('checklist_templates')
    # ### end Alembic commands ###
