"""tabelas_sistema_tenant_nullable

Revision ID: 0a0db412c2c8
Revises: 42735d10bf8c
Create Date: 2026-03-27 19:43:59.260305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0db412c2c8'
down_revision: Union[str, Sequence[str], None] = '42735d10bf8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_commodities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema', sa.Boolean(), nullable=False, server_default='false', comment='True = não editável pelo tenant'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='NULL = padrão do sistema')

    with op.batch_alter_table('cadastros_culturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema', sa.Boolean(), nullable=False, server_default='false', comment='True = não editável pelo tenant'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='NULL = padrão do sistema')

    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='NULL = registro global do sistema')

    with op.batch_alter_table('monitoramento_catalogo', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='NULL = registro global do sistema')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoramento_catalogo', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='NULL = registro global do sistema')

    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='NULL = registro global do sistema')

    with op.batch_alter_table('cadastros_culturas', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='NULL = padrão do sistema')
        batch_op.drop_column('sistema')

    with op.batch_alter_table('cadastros_commodities', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='NULL = padrão do sistema')
        batch_op.drop_column('sistema')

    # ### end Alembic commands ###
