"""reserva_estoque_e_quantidade_reservada

Revision ID: 0be54b7733cc
Revises: a7f302ced8ad
Create Date: 2026-03-23 19:37:13.574964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be54b7733cc'
down_revision: Union[str, Sequence[str], None] = 'a7f302ced8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_reservas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('deposito_id', sa.Uuid(), nullable=False),
    sa.Column('criado_por_id', sa.Uuid(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.Column('referencia_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['deposito_id'], ['estoque_depositos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['estoque_produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estoque_reservas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estoque_reservas_deposito_id'), ['deposito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoque_reservas_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoque_reservas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoque_reservas_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('estoque_saldos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_reservada', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_saldos', schema=None) as batch_op:
        batch_op.drop_column('quantidade_reservada')

    with op.batch_alter_table('estoque_reservas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoque_reservas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_estoque_reservas_status'))
        batch_op.drop_index(batch_op.f('ix_estoque_reservas_produto_id'))
        batch_op.drop_index(batch_op.f('ix_estoque_reservas_deposito_id'))

    op.drop_table('estoque_reservas')
    # ### end Alembic commands ###
