"""financeiro_origem_rastreabilidade

Revision ID: 0e579d47773e
Revises: eaeeac2f9a86
Create Date: 2026-03-27 17:35:57.797521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e579d47773e'
down_revision: Union[str, Sequence[str], None] = 'eaeeac2f9a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fin_despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem_id', sa.Uuid(), nullable=True, comment='ID do registro que gerou esta despesa (ex: operacao_agricola.id)'))
        batch_op.add_column(sa.Column('origem_tipo', sa.String(length=40), nullable=True, comment='Tipo da origem: OPERACAO_AGRICOLA, COMPRA, etc.'))
        batch_op.create_index(batch_op.f('ix_fin_despesas_origem_id'), ['origem_id'], unique=False)

    with op.batch_alter_table('fin_receitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem_id', sa.Uuid(), nullable=True, comment='ID do registro que gerou esta receita (ex: romaneios_colheita.id)'))
        batch_op.add_column(sa.Column('origem_tipo', sa.String(length=40), nullable=True, comment='Tipo da origem: ROMANEIO_COLHEITA, etc.'))
        batch_op.create_index(batch_op.f('ix_fin_receitas_origem_id'), ['origem_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fin_receitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_receitas_origem_id'))
        batch_op.drop_column('origem_tipo')
        batch_op.drop_column('origem_id')

    with op.batch_alter_table('fin_despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_despesas_origem_id'))
        batch_op.drop_column('origem_tipo')
        batch_op.drop_column('origem_id')

    # ### end Alembic commands ###
