"""add_vigencia_to_fazenda_usuario

Revision ID: 16db0dfffb85
Revises: 46646289cedf
Create Date: 2026-04-08 00:01:09.515619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16db0dfffb85'
down_revision: Union[str, Sequence[str], None] = '46646289cedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fazenda_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vigencia_inicio', sa.Date(), nullable=True, comment='Início da vigência do acesso. NULL = imediato'))
        batch_op.add_column(sa.Column('vigencia_fim', sa.Date(), nullable=True, comment='Fim da vigência do acesso. NULL = permanente'))
        batch_op.create_index(batch_op.f('ix_fazenda_usuarios_vigencia_fim'), ['vigencia_fim'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fazenda_usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fazenda_usuarios_vigencia_fim'))
        batch_op.drop_column('vigencia_fim')
        batch_op.drop_column('vigencia_inicio')

    # ### end Alembic commands ###
