"""onda3_pecuaria_animal

Revision ID: 3a5b2924aad1
Revises: ed0688180f35
Create Date: 2026-03-24 23:14:53.500121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a5b2924aad1'
down_revision: Union[str, Sequence[str], None] = 'ed0688180f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pec_lotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=True, comment='Piquete ou pastagem atual (cadastros_areas_rurais)'),
    sa.Column('identificacao', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('raca', sa.String(length=100), nullable=True),
    sa.Column('quantidade_cabecas', sa.Integer(), nullable=False),
    sa.Column('peso_medio_kg', sa.Float(), nullable=False),
    sa.Column('data_formacao', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['cadastros_areas_rurais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pec_lotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pec_lotes_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_lotes_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_lotes_identificacao'), ['identificacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_lotes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pec_animais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('numero_brinco', sa.String(length=50), nullable=True),
    sa.Column('numero_sisbov', sa.String(length=30), nullable=True, comment='SISBOV/Rastreabilidade bovina'),
    sa.Column('microchip', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True, comment='Nome do animal (opcional, comum em reprodutores)'),
    sa.Column('especie', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('raca', sa.String(length=100), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('pelagem', sa.String(length=50), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('pai_id', sa.Uuid(), nullable=True),
    sa.Column('mae_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('peso_atual_kg', sa.Float(), nullable=True),
    sa.Column('data_ultima_pesagem', sa.Date(), nullable=True),
    sa.Column('valor_aquisicao', sa.Float(), nullable=True),
    sa.Column('valor_atual', sa.Float(), nullable=True, comment='Valor de mercado estimado'),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['pec_lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mae_id'], ['pec_animais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pai_id'], ['pec_animais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pec_animais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pec_animais_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_animais_lote_id'), ['lote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_animais_numero_brinco'), ['numero_brinco'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_animais_numero_sisbov'), ['numero_sisbov'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_animais_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pec_eventos_animal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=True, comment='PESAGEM, NASCIMENTO, COMPRA, VENDA, ABATE'),
    sa.Column('valor', sa.Float(), nullable=True, comment='Valor financeiro do evento (COMPRA, VENDA, MEDICACAO...)'),
    sa.Column('lote_destino_id', sa.Uuid(), nullable=True, comment='TRANSFERENCIA_LOTE: lote destino'),
    sa.Column('area_destino_id', sa.Uuid(), nullable=True, comment='Piquete/pastagem destino em transferências'),
    sa.Column('pessoa_id', sa.Uuid(), nullable=True, comment='COMPRA: vendedor | VENDA: comprador | MEDICACAO: veterinário'),
    sa.Column('produto_id', sa.Uuid(), nullable=True, comment='VACINACAO | MEDICACAO | VERMIFUGACAO: produto utilizado'),
    sa.Column('responsavel_id', sa.Uuid(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['pec_animais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['area_destino_id'], ['cadastros_areas_rurais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lote_destino_id'], ['pec_lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['produto_id'], ['cadastros_produtos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pec_eventos_animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pec_eventos_animal_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_eventos_animal_data_evento'), ['data_evento'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_eventos_animal_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_eventos_animal_tipo'), ['tipo'], unique=False)

    op.create_table('pec_producao_leite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=True, comment='Registro individual por animal (alta precisão)'),
    sa.Column('lote_id', sa.Uuid(), nullable=True, comment='Registro coletivo por lote'),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('volume_litros', sa.Float(), nullable=False),
    sa.Column('temperatura_c', sa.Float(), nullable=True),
    sa.Column('gordura_pct', sa.Float(), nullable=True),
    sa.Column('proteina_pct', sa.Float(), nullable=True),
    sa.Column('ccs', sa.Integer(), nullable=True, comment='Contagem de Células Somáticas (x1000/ml)'),
    sa.Column('cbt', sa.Integer(), nullable=True, comment='Contagem Bacteriana Total (x1000/ml)'),
    sa.Column('lactose_pct', sa.Float(), nullable=True),
    sa.Column('esd_pct', sa.Float(), nullable=True, comment='Extrato Seco Desengordurado'),
    sa.Column('destino', sa.String(length=30), nullable=True, comment='LATICINIO | QUEIJARIA | CONSUMO_PROPRIO | DESCARTE'),
    sa.Column('pessoa_destino_id', sa.Uuid(), nullable=True, comment='Laticínio ou comprador'),
    sa.Column('preco_litro', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['pec_animais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['pec_lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pessoa_destino_id'], ['cadastros_pessoas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pec_producao_leite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pec_producao_leite_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_producao_leite_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_producao_leite_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_producao_leite_lote_id'), ['lote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_producao_leite_tenant_id'), ['tenant_id'], unique=False)

    # Remover FK de pec_manejos_lote antes de dropar pec_lotes_bovinos
    with op.batch_alter_table('pec_manejos_lote', schema=None) as batch_op:
        batch_op.alter_column('tipo_evento',
               existing_type=sa.VARCHAR(length=50),
               comment='NASCIMENTO | MORTE | PESAGEM | VACINACAO | TRANSFERENCIA | VENDA | ABATE',
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('pec_manejos_lote_lote_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pec_lotes', ['lote_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pec_lotes_bovinos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_lotes_bovinos_fazenda_id'))
        batch_op.drop_index(batch_op.f('ix_pec_lotes_bovinos_piquete_id'))
        batch_op.drop_index(batch_op.f('ix_pec_lotes_bovinos_tenant_id'))

    op.drop_table('pec_lotes_bovinos')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pec_manejos_lote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pec_manejos_lote_lote_id_fkey'), 'pec_lotes_bovinos', ['lote_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('tipo_evento',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='NASCIMENTO | MORTE | PESAGEM | VACINACAO | TRANSFERENCIA | VENDA | ABATE',
               existing_nullable=False)

    op.create_table('pec_lotes_bovinos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('piquete_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('identificacao', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('raca', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quantidade_cabecas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peso_medio_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('data_formacao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], name=op.f('pec_lotes_bovinos_fazenda_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piquete_id'], ['pec_piquetes.id'], name=op.f('pec_lotes_bovinos_piquete_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('pec_lotes_bovinos_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pec_lotes_bovinos_pkey'))
    )
    with op.batch_alter_table('pec_lotes_bovinos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pec_lotes_bovinos_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_lotes_bovinos_piquete_id'), ['piquete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pec_lotes_bovinos_fazenda_id'), ['fazenda_id'], unique=False)

    with op.batch_alter_table('pec_producao_leite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_producao_leite_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pec_producao_leite_lote_id'))
        batch_op.drop_index(batch_op.f('ix_pec_producao_leite_fazenda_id'))
        batch_op.drop_index(batch_op.f('ix_pec_producao_leite_data'))
        batch_op.drop_index(batch_op.f('ix_pec_producao_leite_animal_id'))

    op.drop_table('pec_producao_leite')
    with op.batch_alter_table('pec_eventos_animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_eventos_animal_tipo'))
        batch_op.drop_index(batch_op.f('ix_pec_eventos_animal_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pec_eventos_animal_data_evento'))
        batch_op.drop_index(batch_op.f('ix_pec_eventos_animal_animal_id'))

    op.drop_table('pec_eventos_animal')
    with op.batch_alter_table('pec_animais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_animais_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pec_animais_numero_sisbov'))
        batch_op.drop_index(batch_op.f('ix_pec_animais_numero_brinco'))
        batch_op.drop_index(batch_op.f('ix_pec_animais_lote_id'))
        batch_op.drop_index(batch_op.f('ix_pec_animais_fazenda_id'))

    op.drop_table('pec_animais')
    with op.batch_alter_table('pec_lotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_lotes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pec_lotes_identificacao'))
        batch_op.drop_index(batch_op.f('ix_pec_lotes_fazenda_id'))
        batch_op.drop_index(batch_op.f('ix_pec_lotes_area_id'))

    op.drop_table('pec_lotes')
    # ### end Alembic commands ###
