"""Add fase and criticidade to SafraTarefa and bypass to SafraFaseHistorico

Revision ID: 3e5cb19a3727
Revises: ef4c538525d1
Create Date: 2026-04-22 16:04:35.726546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5cb19a3727'
down_revision: Union[str, Sequence[str], None] = 'ef4c538525d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safra_fase_historico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forcou_avanco', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('justificativa_avanco', sa.Text(), nullable=True))

    with op.batch_alter_table('safra_tarefas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('criticidade', sa.String(length=15), nullable=False, server_default=sa.text("'NORMAL'")))
        batch_op.create_index(batch_op.f('ix_safra_tarefas_fase'), ['fase'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safra_tarefas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safra_tarefas_fase'))
        batch_op.drop_column('criticidade')
        batch_op.drop_column('fase')

    with op.batch_alter_table('safra_fase_historico', schema=None) as batch_op:
        batch_op.drop_column('justificativa_avanco')
        batch_op.drop_column('forcou_avanco')

    # ### end Alembic commands ###
