"""add_plan_changes_and_dynamic_pricing

Revision ID: 4492badc2748
Revises: 20240312_multi_sub
Create Date: 2026-03-15 00:09:30.132458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4492badc2748'
down_revision: Union[str, Sequence[str], None] = '20240312_multi_sub'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano_pricing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plano_id', sa.Uuid(), nullable=False),
    sa.Column('faixa_inicio', sa.Integer(), nullable=False, comment='Início da faixa (inclusivo)'),
    sa.Column('faixa_fim', sa.Integer(), nullable=True, comment='Fim da faixa (inclusivo). NULL = ilimitado'),
    sa.Column('preco_por_usuario_mensal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_por_usuario_anual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos_assinatura.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plano_pricing', schema=None) as batch_op:
        batch_op.create_index('idx_plano_faixa', ['plano_id', 'faixa_inicio', 'faixa_fim'], unique=False)
        batch_op.create_index(batch_op.f('ix_plano_pricing_plano_id'), ['plano_id'], unique=False)

    op.create_table('mudancas_plano',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('assinatura_id', sa.Uuid(), nullable=False),
    sa.Column('plano_origem_id', sa.Uuid(), nullable=False),
    sa.Column('usuarios_origem', sa.Integer(), nullable=False),
    sa.Column('plano_destino_id', sa.Uuid(), nullable=False),
    sa.Column('usuarios_destino', sa.Integer(), nullable=False),
    sa.Column('tipo_mudanca', sa.String(length=30), nullable=False, comment='UPGRADE_PLANO, DOWNGRADE_PLANO, UPGRADE_USUARIOS, DOWNGRADE_USUARIOS, UPGRADE_COMPLETO, DOWNGRADE_COMPLETO'),
    sa.Column('valor_calculado', sa.Numeric(precision=10, scale=2), nullable=False, comment='Valor a ser cobrado (upgrade) ou creditado (downgrade futuro)'),
    sa.Column('valor_proporcional', sa.Numeric(precision=10, scale=2), nullable=False, comment='Valor proporcional aos dias restantes do ciclo'),
    sa.Column('dias_restantes_ciclo', sa.Integer(), nullable=True),
    sa.Column('cobranca_asaas_id', sa.String(length=100), nullable=True),
    sa.Column('url_pagamento', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False, comment='pendente_pagamento, liberado_manualmente, pago, aplicado, bloqueado, cancelado'),
    sa.Column('liberado_manualmente', sa.Boolean(), nullable=False),
    sa.Column('aprovado_por_admin_id', sa.Uuid(), nullable=True),
    sa.Column('motivo_liberacao_manual', sa.Text(), nullable=True),
    sa.Column('data_limite_pagamento', sa.DateTime(timezone=True), nullable=True, comment='Prazo para regularizar pagamento em caso de liberação manual'),
    sa.Column('solicitado_por_usuario_id', sa.Uuid(), nullable=False),
    sa.Column('aplicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aplicado_por_job', sa.Boolean(), nullable=False),
    sa.Column('agendado_para', sa.DateTime(timezone=True), nullable=True, comment='Data de aplicação agendada (usado em downgrades)'),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprovado_por_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas_tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plano_destino_id'], ['planos_assinatura.id'], ),
    sa.ForeignKeyConstraint(['plano_origem_id'], ['planos_assinatura.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mudancas_plano', schema=None) as batch_op:
        batch_op.create_index('idx_mudanca_agendado', ['agendado_para'], unique=False)
        batch_op.create_index('idx_mudanca_status_tenant', ['status', 'tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mudancas_plano_assinatura_id'), ['assinatura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mudancas_plano_cobranca_asaas_id'), ['cobranca_asaas_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_mudancas_plano_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mudancas_plano_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cobrancas_asaas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('mudanca_plano_id', sa.Uuid(), nullable=True),
    sa.Column('assinatura_id', sa.Uuid(), nullable=True),
    sa.Column('asaas_charge_id', sa.String(length=100), nullable=False),
    sa.Column('asaas_customer_id', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False, comment='PENDING, RECEIVED, CONFIRMED, OVERDUE, REFUNDED, RECEIVED_IN_CASH, REFUND_REQUESTED, CHARGEBACK_REQUESTED, CHARGEBACK_DISPUTE, AWAITING_CHARGEBACK_REVERSAL, DUNNING_REQUESTED, DUNNING_RECEIVED, AWAITING_RISK_ANALYSIS'),
    sa.Column('url_pagamento', sa.String(length=500), nullable=True),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('qrcode_pix', sa.Text(), nullable=True),
    sa.Column('data_vencimento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_webhook_recebido', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas_tenant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mudanca_plano_id'], ['mudancas_plano.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cobrancas_asaas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cobrancas_asaas_asaas_charge_id'), ['asaas_charge_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cobrancas_asaas_mudanca_plano_id'), ['mudanca_plano_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobrancas_asaas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cobrancas_asaas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('historico_bloqueios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('mudanca_plano_id', sa.Uuid(), nullable=True),
    sa.Column('assinatura_id', sa.Uuid(), nullable=True),
    sa.Column('motivo', sa.String(length=50), nullable=False, comment='INADIMPLENCIA_MUDANCA_PLANO, INADIMPLENCIA_MENSALIDADE, VIOLACAO_TERMOS, MANUAL'),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_bloqueio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_desbloqueio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bloqueado_por_admin_id', sa.Uuid(), nullable=True),
    sa.Column('desbloqueado_por_admin_id', sa.Uuid(), nullable=True),
    sa.Column('bloqueado_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas_tenant.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bloqueado_por_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['desbloqueado_por_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['mudanca_plano_id'], ['mudancas_plano.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico_bloqueios', schema=None) as batch_op:
        batch_op.create_index('idx_bloqueio_tenant_data', ['tenant_id', 'data_bloqueio'], unique=False)
        batch_op.create_index(batch_op.f('ix_historico_bloqueios_tenant_id'), ['tenant_id'], unique=False)

    op.drop_table('alembic_version')

    # Adicionar coluna usuarios_contratados como nullable primeiro
    with op.batch_alter_table('assinaturas_tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuarios_contratados', sa.Integer(), nullable=True, comment='Quantidade de usuários simultâneos contratados'))
        batch_op.add_column(sa.Column('data_bloqueio', sa.DateTime(timezone=True), nullable=True, comment='Data do último bloqueio'))

    # Preencher valores default para registros existentes
    op.execute("UPDATE assinaturas_tenant SET usuarios_contratados = 5 WHERE usuarios_contratados IS NULL")

    # Agora tornar NOT NULL
    with op.batch_alter_table('assinaturas_tenant', schema=None) as batch_op:
        batch_op.alter_column('usuarios_contratados', nullable=False)

    # Adicionar colunas de limite de usuários em planos
    with op.batch_alter_table('planos_assinatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limite_usuarios_minimo', sa.Integer(), nullable=True, comment='Quantidade mínima de usuários para este plano'))
        batch_op.add_column(sa.Column('limite_usuarios_maximo', sa.Integer(), nullable=True, comment='Quantidade máxima de usuários. NULL = ilimitado'))

    # Preencher valores default para planos existentes
    op.execute("UPDATE planos_assinatura SET limite_usuarios_minimo = 1 WHERE limite_usuarios_minimo IS NULL")

    # Tornar limite_usuarios_minimo NOT NULL
    with op.batch_alter_table('planos_assinatura', schema=None) as batch_op:
        batch_op.alter_column('limite_usuarios_minimo', nullable=False)
        batch_op.alter_column('limite_usuarios',
               existing_type=sa.INTEGER(),
               comment='DEPRECATED: valor de referência apenas',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos_assinatura', schema=None) as batch_op:
        batch_op.alter_column('limite_usuarios',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='DEPRECATED: valor de referência apenas',
               existing_nullable=False)
        batch_op.drop_column('limite_usuarios_maximo')
        batch_op.drop_column('limite_usuarios_minimo')

    with op.batch_alter_table('assinaturas_tenant', schema=None) as batch_op:
        batch_op.drop_column('data_bloqueio')
        batch_op.drop_column('usuarios_contratados')

    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    with op.batch_alter_table('historico_bloqueios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_bloqueios_tenant_id'))
        batch_op.drop_index('idx_bloqueio_tenant_data')

    op.drop_table('historico_bloqueios')
    with op.batch_alter_table('cobrancas_asaas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cobrancas_asaas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cobrancas_asaas_status'))
        batch_op.drop_index(batch_op.f('ix_cobrancas_asaas_mudanca_plano_id'))
        batch_op.drop_index(batch_op.f('ix_cobrancas_asaas_asaas_charge_id'))

    op.drop_table('cobrancas_asaas')
    with op.batch_alter_table('mudancas_plano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mudancas_plano_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mudancas_plano_status'))
        batch_op.drop_index(batch_op.f('ix_mudancas_plano_cobranca_asaas_id'))
        batch_op.drop_index(batch_op.f('ix_mudancas_plano_assinatura_id'))
        batch_op.drop_index('idx_mudanca_status_tenant')
        batch_op.drop_index('idx_mudanca_agendado')

    op.drop_table('mudancas_plano')
    with op.batch_alter_table('plano_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_pricing_plano_id'))
        batch_op.drop_index('idx_plano_faixa')

    op.drop_table('plano_pricing')
    # ### end Alembic commands ###
