"""add_localizacao_tipo_to_fazendas_decimal_area_rural

Revision ID: 46646289cedf
Revises: f58b4e673940
Create Date: 2026-04-07 23:57:03.006069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46646289cedf'
down_revision: Union[str, Sequence[str], None] = 'f58b4e673940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_areas_rurais', schema=None) as batch_op:
        batch_op.alter_column('area_hectares',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=4),
               existing_comment='Calculado do polígono ou preenchido manualmente',
               existing_nullable=True)
        batch_op.alter_column('area_hectares_manual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=4),
               existing_comment='Override manual quando não há geometria',
               existing_nullable=True)

    with op.batch_alter_table('fazendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_propriedade', sa.String(length=30), nullable=False, server_default='fazenda', comment='fazenda | sitio | chacara | arrendamento | parceria'))
        batch_op.add_column(sa.Column('ccir', sa.String(length=30), nullable=True, comment='Certificado de Cadastro de Imóvel Rural (INCRA)'))
        batch_op.add_column(sa.Column('sigef_codigo', sa.String(length=50), nullable=True, comment='Código SIGEF (INCRA georreferenciamento)'))
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ibge_municipio_codigo', sa.String(length=7), nullable=True, comment='Código IBGE do município'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fazendas', schema=None) as batch_op:
        batch_op.drop_column('ibge_municipio_codigo')
        batch_op.drop_column('bairro')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cep')
        batch_op.drop_column('sigef_codigo')
        batch_op.drop_column('ccir')
        batch_op.drop_column('tipo_propriedade')

    with op.batch_alter_table('cadastros_areas_rurais', schema=None) as batch_op:
        batch_op.alter_column('area_hectares_manual',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Override manual quando não há geometria',
               existing_nullable=True)
        batch_op.alter_column('area_hectares',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Calculado do polígono ou preenchido manualmente',
               existing_nullable=True)

    # ### end Alembic commands ###
