"""analises_solo

Revision ID: 4b6b337b818f
Revises: abbf2ef99219
Create Date: 2026-03-27 16:46:29.786832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6b337b818f'
down_revision: Union[str, Sequence[str], None] = 'abbf2ef99219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analises_solo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('data_coleta', sa.Date(), nullable=False),
    sa.Column('laboratorio', sa.String(length=150), nullable=True),
    sa.Column('codigo_amostra', sa.String(length=50), nullable=True),
    sa.Column('profundidade_cm', sa.Numeric(precision=3, scale=0), nullable=True),
    sa.Column('argila_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('silte_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('areia_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ph_agua', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ph_cacl2', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('materia_organica_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fosforo_p', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('potassio_k', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('calcio_ca', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('magnesio_mg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('aluminio_al', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('hidrogenio_al_hal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ctc', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('v_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('arquivo_laudo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['talhao_id'], ['cadastros_areas_rurais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analises_solo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analises_solo_talhao_id'), ['talhao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analises_solo_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analises_solo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analises_solo_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_analises_solo_talhao_id'))

    op.drop_table('analises_solo')
    # ### end Alembic commands ###
