"""pii_add_pj_fields

Revision ID: 556b7b957de3
Revises: 4e0b633ffb18
Create Date: 2026-03-25 00:51:55.247492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556b7b957de3'
down_revision: Union[str, Sequence[str], None] = '4e0b633ffb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastros_pessoas_pii',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('nome_completo', sa.String(length=300), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=30), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('nome_mae', sa.String(length=200), nullable=True),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('ie', sa.String(length=30), nullable=True, comment='Inscrição Estadual'),
    sa.Column('data_fundacao', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_pessoas_pii', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_pii_pessoa_id'), ['pessoa_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_pessoas_pii', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_pii_pessoa_id'))

    op.drop_table('cadastros_pessoas_pii')
    # ### end Alembic commands ###
