"""add_frota_maquinario_structured_fields

Revision ID: 5acaf7be91a8
Revises: ea1498232c05
Create Date: 2026-03-22 23:41:55.669418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acaf7be91a8'
down_revision: Union[str, Sequence[str], None] = 'ea1498232c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frota_maquinarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_serie', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('patrimonio', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('combustivel', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('potencia_cv', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('capacidade_tanque_l', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frota_maquinarios', schema=None) as batch_op:
        batch_op.drop_column('capacidade_tanque_l')
        batch_op.drop_column('potencia_cv')
        batch_op.drop_column('combustivel')
        batch_op.drop_column('patrimonio')
        batch_op.drop_column('numero_serie')

    # ### end Alembic commands ###
