"""create_pessoas_table

Revision ID: 5d371c3cd756
Revises: 5563c3f1a6d4
Create Date: 2026-03-22 22:28:56.030977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d371c3cd756'
down_revision: Union[str, Sequence[str], None] = '5563c3f1a6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_principal', sa.String(length=20), nullable=False, comment='FORNECEDOR, CLIENTE, FUNCIONARIO, PARCEIRO, PRESTADOR, OUTRO'),
    sa.Column('tipos', sa.JSON(), nullable=False, comment="Lista de todos os tipos aplicáveis (ex: ['FORNECEDOR', 'CLIENTE'])"),
    sa.Column('tipo_pessoa', sa.String(length=2), nullable=False, comment='PF (pessoa física) ou PJ (pessoa jurídica)'),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('rg_ie', sa.String(length=30), nullable=True, comment='RG (PF) ou Inscrição Estadual (PJ)'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('banco_codigo', sa.String(length=10), nullable=True),
    sa.Column('banco_agencia', sa.String(length=10), nullable=True),
    sa.Column('banco_conta', sa.String(length=20), nullable=True),
    sa.Column('banco_tipo_conta', sa.String(length=20), nullable=True, comment='CORRENTE, POUPANCA, PIX'),
    sa.Column('banco_chave_pix', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoas_cpf_cnpj'), ['cpf_cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoas_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoas_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pessoas_nome'))
        batch_op.drop_index(batch_op.f('ix_pessoas_cpf_cnpj'))

    op.drop_table('pessoas')
    # ### end Alembic commands ###
