"""produtos_marcas_modelos_categorias

Revision ID: 5d3bfcf20877
Revises: 06d9e4c7ed54
Create Date: 2026-03-25 21:57:50.429404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3bfcf20877'
down_revision: Union[str, Sequence[str], None] = '06d9e4c7ed54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastros_categorias_produto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True, comment='Hex color para UI, ex: #4CAF50'),
    sa.Column('icone', sa.String(length=50), nullable=True, comment='Nome de ícone (lucide/heroicons)'),
    sa.Column('ordem', sa.Integer(), nullable=False, comment='Ordem de exibição dentro do pai'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['cadastros_categorias_produto.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', 'parent_id', name='uq_categoria_tenant_nome_parent')
    )
    with op.batch_alter_table('cadastros_categorias_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_categorias_produto_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_categorias_produto_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_categorias_produto_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cadastros_marcas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('pais_origem', sa.String(length=60), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'nome', name='uq_marca_tenant_nome')
    )
    with op.batch_alter_table('cadastros_marcas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_marcas_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_marcas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cadastros_modelos_produto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('marca_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True, comment='Código/referência do fabricante'),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_produto', sa.String(length=30), nullable=True, comment='TipoProduto compatível, ou null p/ qualquer'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['cadastros_marcas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'marca_id', 'nome', name='uq_modelo_tenant_marca_nome')
    )
    with op.batch_alter_table('cadastros_modelos_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_modelos_produto_marca_id'), ['marca_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_modelos_produto_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_modelos_produto_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('cadastros_produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('modelo_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('referencia_fabricante', sa.String(length=100), nullable=True, comment='Código/part number do fabricante'))
        batch_op.add_column(sa.Column('categoria_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('imagem_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('preco_ultima_compra', sa.Float(), nullable=True))
        batch_op.alter_column('marca',
               existing_type=sa.VARCHAR(length=100),
               comment='Fallback quando marca_id é null',
               existing_nullable=True)
        batch_op.alter_column('fabricante',
               existing_type=sa.VARCHAR(length=100),
               comment='Razão social do fabricante',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_cadastros_produtos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_produtos_marca_id'), ['marca_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_produtos_modelo_id'), ['modelo_id'], unique=False)
        batch_op.create_foreign_key(None, 'cadastros_marcas', ['marca_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'cadastros_modelos_produto', ['modelo_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'cadastros_categorias_produto', ['categoria_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cadastros_produtos_agricola', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composicao_npk', sa.String(length=50), nullable=True, comment='ex: 10-10-10, 00-18-00'))
        batch_op.add_column(sa.Column('densidade_g_ml', sa.Float(), nullable=True))

    with op.batch_alter_table('cadastros_produtos_epi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamanho', sa.String(length=20), nullable=True, comment='PP | P | M | G | GG | UNICO'))

    with op.batch_alter_table('cadastros_produtos_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lote_controlado', sa.Boolean(), nullable=False, comment='Controle por lote/série no estoque'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_produtos_estoque', schema=None) as batch_op:
        batch_op.drop_column('lote_controlado')

    with op.batch_alter_table('cadastros_produtos_epi', schema=None) as batch_op:
        batch_op.drop_column('tamanho')

    with op.batch_alter_table('cadastros_produtos_agricola', schema=None) as batch_op:
        batch_op.drop_column('densidade_g_ml')
        batch_op.drop_column('composicao_npk')

    with op.batch_alter_table('cadastros_produtos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cadastros_produtos_modelo_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_produtos_marca_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_produtos_categoria_id'))
        batch_op.alter_column('fabricante',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Razão social do fabricante',
               existing_nullable=True)
        batch_op.alter_column('marca',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Fallback quando marca_id é null',
               existing_nullable=True)
        batch_op.drop_column('preco_ultima_compra')
        batch_op.drop_column('imagem_url')
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('referencia_fabricante')
        batch_op.drop_column('modelo_id')
        batch_op.drop_column('marca_id')

    with op.batch_alter_table('cadastros_modelos_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_modelos_produto_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_modelos_produto_nome'))
        batch_op.drop_index(batch_op.f('ix_cadastros_modelos_produto_marca_id'))

    op.drop_table('cadastros_modelos_produto')
    with op.batch_alter_table('cadastros_marcas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_marcas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_marcas_nome'))

    op.drop_table('cadastros_marcas')
    with op.batch_alter_table('cadastros_categorias_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_categorias_produto_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_categorias_produto_parent_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_categorias_produto_nome'))

    op.drop_table('cadastros_categorias_produto')
    # ### end Alembic commands ###
