"""onda1_lotes_recebimento_parcial_devolucao_requisicao

Revision ID: 5f203e4d3e53
Revises: 14332b81c8b9
Create Date: 2026-03-23 19:00:43.445220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f203e4d3e53'
down_revision: Union[str, Sequence[str], None] = '14332b81c8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_requisicoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('solicitante_id', sa.Uuid(), nullable=False),
    sa.Column('aprovador_id', sa.Uuid(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_necessidade', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origem_tipo', sa.String(length=30), nullable=False),
    sa.Column('origem_id', sa.Uuid(), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['aprovador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estoque_requisicoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estoque_requisicoes_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoque_requisicoes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('estoque_lotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('deposito_id', sa.Uuid(), nullable=False),
    sa.Column('numero_lote', sa.String(length=100), nullable=False),
    sa.Column('data_fabricacao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('quantidade_inicial', sa.Float(), nullable=False),
    sa.Column('quantidade_atual', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.Column('nota_fiscal_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deposito_id'], ['estoque_depositos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['estoque_produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estoque_lotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estoque_lotes_data_validade'), ['data_validade'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoque_lotes_deposito_id'), ['deposito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoque_lotes_numero_lote'), ['numero_lote'], unique=False)
        batch_op.create_index(batch_op.f('ix_estoque_lotes_produto_id'), ['produto_id'], unique=False)

    op.create_table('compras_devolucoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=True),
    sa.Column('fornecedor_id', sa.Uuid(), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('numero_nf_devolucao', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['compras_fornecedores.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['compras_pedidos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compras_devolucoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compras_devolucoes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('compras_recebimentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('data_recebimento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('numero_nf', sa.String(length=50), nullable=True),
    sa.Column('chave_nfe', sa.String(length=60), nullable=True),
    sa.Column('recebido_por_id', sa.Uuid(), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['compras_pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recebido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compras_recebimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compras_recebimentos_pedido_id'), ['pedido_id'], unique=False)

    op.create_table('estoque_requisicoes_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requisicao_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('deposito_id', sa.Uuid(), nullable=True),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('quantidade_solicitada', sa.Float(), nullable=False),
    sa.Column('quantidade_aprovada', sa.Float(), nullable=True),
    sa.Column('quantidade_entregue', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deposito_id'], ['estoque_depositos.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['estoque_lotes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['estoque_produtos.id'], ),
    sa.ForeignKeyConstraint(['requisicao_id'], ['estoque_requisicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras_devolucoes_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('devolucao_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('deposito_origem_id', sa.Uuid(), nullable=False),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['deposito_origem_id'], ['estoque_depositos.id'], ),
    sa.ForeignKeyConstraint(['devolucao_id'], ['compras_devolucoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['estoque_lotes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['estoque_produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras_recebimentos_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recebimento_id', sa.Uuid(), nullable=False),
    sa.Column('item_pedido_id', sa.Uuid(), nullable=False),
    sa.Column('quantidade_recebida', sa.Float(), nullable=False),
    sa.Column('preco_real_unitario', sa.Float(), nullable=False),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['item_pedido_id'], ['compras_itens_pedido.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['estoque_lotes.id'], ),
    sa.ForeignKeyConstraint(['recebimento_id'], ['compras_recebimentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compras_itens_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_item', sa.String(length=20), nullable=False))
        batch_op.alter_column('quantidade_recebida',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('estoque_movimentacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lote_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'estoque_lotes', ['lote_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_movimentacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lote_id')

    with op.batch_alter_table('compras_itens_pedido', schema=None) as batch_op:
        batch_op.alter_column('quantidade_recebida',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('status_item')

    op.drop_table('compras_recebimentos_itens')
    op.drop_table('compras_devolucoes_itens')
    op.drop_table('estoque_requisicoes_itens')
    with op.batch_alter_table('compras_recebimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compras_recebimentos_pedido_id'))

    op.drop_table('compras_recebimentos')
    with op.batch_alter_table('compras_devolucoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compras_devolucoes_tenant_id'))

    op.drop_table('compras_devolucoes')
    with op.batch_alter_table('estoque_lotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoque_lotes_produto_id'))
        batch_op.drop_index(batch_op.f('ix_estoque_lotes_numero_lote'))
        batch_op.drop_index(batch_op.f('ix_estoque_lotes_deposito_id'))
        batch_op.drop_index(batch_op.f('ix_estoque_lotes_data_validade'))

    op.drop_table('estoque_lotes')
    with op.batch_alter_table('estoque_requisicoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoque_requisicoes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_estoque_requisicoes_fazenda_id'))

    op.drop_table('estoque_requisicoes')
    # ### end Alembic commands ###
