"""add_rh_departamentos

Revision ID: 60cf3fe20cfc
Revises: 43cdf769d080
Create Date: 2026-04-04 14:46:55.048723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60cf3fe20cfc'
down_revision: Union[str, Sequence[str], None] = '43cdf769d080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rh_departamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('responsavel_nome', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rh_departamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rh_departamentos_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('rh_colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departamento_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rh_colaboradores_departamento_id'), ['departamento_id'], unique=False)
        batch_op.create_foreign_key(None, 'rh_departamentos', ['departamento_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rh_colaboradores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_rh_colaboradores_departamento_id'))
        batch_op.drop_column('departamento_id')

    with op.batch_alter_table('rh_departamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rh_departamentos_tenant_id'))

    op.drop_table('rh_departamentos')
    # ### end Alembic commands ###
