"""add consorciado field to cultivos

Revision ID: 66185fcdafb2
Revises: 461af4a1a386
Create Date: 2026-04-18 15:01:59.368425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66185fcdafb2'
down_revision: Union[str, Sequence[str], None] = '461af4a1a386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas_tecnicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitas_tecnicas_safra_id'))
        batch_op.drop_index(batch_op.f('ix_visitas_tecnicas_talhao_id'))
        batch_op.drop_index(batch_op.f('ix_visitas_tecnicas_tenant_id'))

    op.drop_table('visitas_tecnicas')
    with op.batch_alter_table('caderno_campo_entradas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caderno_campo_entradas_data_registro'))
        batch_op.drop_index(batch_op.f('ix_caderno_campo_entradas_safra_id'))
        batch_op.drop_index(batch_op.f('ix_caderno_campo_entradas_talhao_id'))
        batch_op.drop_index(batch_op.f('ix_caderno_campo_entradas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_caderno_campo_entradas_tipo'))

    op.drop_table('caderno_campo_entradas')
    with op.batch_alter_table('epi_entregas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epi_entregas_tenant_id'))

    op.drop_table('epi_entregas')
    with op.batch_alter_table('caderno_exportacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caderno_exportacoes_safra_id'))
        batch_op.drop_index(batch_op.f('ix_caderno_exportacoes_tenant_id'))

    op.drop_table('caderno_exportacoes')
    with op.batch_alter_table('caderno_campo_fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caderno_campo_fotos_entrada_id'))

    op.drop_table('caderno_campo_fotos')
    with op.batch_alter_table('financeiro_comercializacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financeiro_comercializacoes_commodity_id'))
        batch_op.drop_index(batch_op.f('ix_financeiro_comercializacoes_comprador_id'))
        batch_op.drop_index(batch_op.f('ix_financeiro_comercializacoes_numero_contrato'))
        batch_op.drop_index(batch_op.f('ix_financeiro_comercializacoes_produto_colhido_id'))
        batch_op.drop_index(batch_op.f('ix_financeiro_comercializacoes_status'))
        batch_op.drop_index(batch_op.f('ix_financeiro_comercializacoes_tenant_id'))

    op.drop_table('financeiro_comercializacoes')
    with op.batch_alter_table('agricola_operacao_tipo_fase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agricola_operacao_tipo_fase_tipo_operacao'))

    op.drop_table('agricola_operacao_tipo_fase')
    with op.batch_alter_table('agricola_produtos_colhidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agricola_produtos_colhidos_classificacao_id'))
        batch_op.drop_index(batch_op.f('ix_agricola_produtos_colhidos_commodity_id'))
        batch_op.drop_index(batch_op.f('ix_agricola_produtos_colhidos_romaneio_id'))
        batch_op.drop_index(batch_op.f('ix_agricola_produtos_colhidos_safra_id'))
        batch_op.drop_index(batch_op.f('ix_agricola_produtos_colhidos_status'))
        batch_op.drop_index(batch_op.f('ix_agricola_produtos_colhidos_talhao_id'))
        batch_op.drop_index(batch_op.f('ix_agricola_produtos_colhidos_tenant_id'))

    op.drop_table('agricola_produtos_colhidos')
    with op.batch_alter_table('agricola_orcamento_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultivo_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agricola_orcamento_itens_cultivo_id'), ['cultivo_id'], unique=False)
        batch_op.create_foreign_key(None, 'cultivos', ['cultivo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cadastros_commodities', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL = padrão do sistema',
               existing_nullable=True)
        batch_op.alter_column('sistema',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True = não editável pelo tenant',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('peso_unidade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Peso em kg da unidade padrão. Obrigatório para SACA_60KG, TONELADA, KG, ARROBA. Null para CABECA, LITRO, etc.',
               existing_nullable=True)
        batch_op.alter_column('umidade_padrao_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Umidade padrão MAPA para descontos. Ex: 14.0 para soja, 12.0 para café',
               existing_nullable=True)
        batch_op.alter_column('impureza_padrao_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Impureza padrão aceita sem desconto. Ex: 1.0',
               existing_nullable=True)
        batch_op.alter_column('possui_cotacao',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('cadastros_commodities_classificacoes', schema=None) as batch_op:
        batch_op.alter_column('classe',
               existing_type=sa.VARCHAR(length=50),
               comment='TIPO_1 | TIPO_2 | FORA_TIPO | ESPECIAL | PREMIUM',
               existing_nullable=False)
        batch_op.alter_column('desconto_umidade_por_ponto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Desconto % por ponto de umidade acima do máximo',
               existing_nullable=True)
        batch_op.alter_column('desconto_impureza_por_ponto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Desconto % por ponto de impureza acima do máximo',
               existing_nullable=True)
        batch_op.alter_column('parametros_extras',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('cadastros_commodities_cotacoes', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='Preço na unidade padrão da commodity',
               existing_nullable=False)
        batch_op.alter_column('fonte',
               existing_type=sa.VARCHAR(length=50),
               comment='Fonte da cotação: CEPEA, B3, CONAB, MANUAL',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('cadastros_conversao_unidades', schema=None) as batch_op:
        batch_op.alter_column('fator',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='destino = origem × fator',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('cadastros_produtos_agricola', schema=None) as batch_op:
        batch_op.alter_column('principio_ativo',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('cafe_lote_beneficiamento_romaneios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('cafe_lotes_beneficiamento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cafe_lotes_beneficiamento_cultivo_id'), type_='foreignkey')
        batch_op.drop_column('cultivo_id')

    with op.batch_alter_table('cultivo_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cultivo_areas_area_id'), ['area_id'], unique=False)

    with op.batch_alter_table('cultivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consorciado', sa.Boolean(), nullable=False))

    with op.batch_alter_table('operacoes_agricolas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_operacoes_agricolas_cultivo_id'), type_='foreignkey')
        batch_op.drop_column('cultivo_id')

    with op.batch_alter_table('romaneios_colheita', schema=None) as batch_op:
        batch_op.alter_column('commodity_id',
               existing_type=sa.UUID(),
               comment='Commodity colhida (derivada de safra.commodity_id, mas explícito para queries)',
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_romaneios_colheita_cultivo_id'), type_='foreignkey')
        batch_op.drop_column('cultivo_id')

    with op.batch_alter_table('safras', schema=None) as batch_op:
        batch_op.alter_column('cultura',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('safras_cultivar_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('safras_commodity_id_fkey'), type_='foreignkey')
        batch_op.drop_column('data_plantio_real')
        batch_op.drop_column('data_colheita_real')
        batch_op.drop_column('preco_venda_previsto')
        batch_op.drop_column('produtividade_meta_sc_ha')
        batch_op.drop_column('area_plantada_ha')
        batch_op.drop_column('commodity_id')
        batch_op.drop_column('data_colheita_prevista')
        batch_op.drop_column('sistema_plantio')
        batch_op.drop_column('data_plantio_prevista')
        batch_op.drop_column('cultivar_id')
        batch_op.drop_column('populacao_prevista')
        batch_op.drop_column('espacamento_cm')
        batch_op.drop_column('cultivar_nome')
        batch_op.drop_column('custo_realizado_ha')
        batch_op.drop_column('produtividade_real_sc_ha')
        batch_op.drop_column('custo_previsto_ha')
        batch_op.drop_column('populacao_real')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('populacao_real', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custo_previsto_ha', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('produtividade_real_sc_ha', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custo_realizado_ha', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cultivar_nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('espacamento_cm', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('populacao_prevista', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cultivar_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_plantio_prevista', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sistema_plantio', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_colheita_prevista', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commodity_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('area_plantada_ha', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('produtividade_meta_sc_ha', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preco_venda_previsto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_colheita_real', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_plantio_real', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('safras_commodity_id_fkey'), 'cadastros_commodities', ['commodity_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('safras_cultivar_id_fkey'), 'cadastros_culturas', ['cultivar_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('cultura',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('romaneios_colheita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultivo_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_romaneios_colheita_cultivo_id'), 'cultivos', ['cultivo_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('commodity_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Commodity colhida (derivada de safra.commodity_id, mas explícito para queries)',
               existing_nullable=True)

    with op.batch_alter_table('operacoes_agricolas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultivo_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_operacoes_agricolas_cultivo_id'), 'cultivos', ['cultivo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cultivos', schema=None) as batch_op:
        batch_op.drop_column('consorciado')

    with op.batch_alter_table('cultivo_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cultivo_areas_area_id'))

    with op.batch_alter_table('cafe_lotes_beneficiamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultivo_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cafe_lotes_beneficiamento_cultivo_id'), 'cultivos', ['cultivo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cafe_lote_beneficiamento_romaneios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('cadastros_produtos_agricola', schema=None) as batch_op:
        batch_op.alter_column('principio_ativo',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    with op.batch_alter_table('cadastros_conversao_unidades', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('fator',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='destino = origem × fator',
               existing_nullable=False)

    with op.batch_alter_table('cadastros_commodities_cotacoes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('fonte',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Fonte da cotação: CEPEA, B3, CONAB, MANUAL',
               existing_nullable=True)
        batch_op.alter_column('preco',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment=None,
               existing_comment='Preço na unidade padrão da commodity',
               existing_nullable=False)

    with op.batch_alter_table('cadastros_commodities_classificacoes', schema=None) as batch_op:
        batch_op.alter_column('parametros_extras',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('desconto_impureza_por_ponto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Desconto % por ponto de impureza acima do máximo',
               existing_nullable=True)
        batch_op.alter_column('desconto_umidade_por_ponto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Desconto % por ponto de umidade acima do máximo',
               existing_nullable=True)
        batch_op.alter_column('classe',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='TIPO_1 | TIPO_2 | FORA_TIPO | ESPECIAL | PREMIUM',
               existing_nullable=False)

    with op.batch_alter_table('cadastros_commodities', schema=None) as batch_op:
        batch_op.alter_column('possui_cotacao',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('impureza_padrao_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Impureza padrão aceita sem desconto. Ex: 1.0',
               existing_nullable=True)
        batch_op.alter_column('umidade_padrao_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Umidade padrão MAPA para descontos. Ex: 14.0 para soja, 12.0 para café',
               existing_nullable=True)
        batch_op.alter_column('peso_unidade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Peso em kg da unidade padrão. Obrigatório para SACA_60KG, TONELADA, KG, ARROBA. Null para CABECA, LITRO, etc.',
               existing_nullable=True)
        batch_op.alter_column('sistema',
               existing_type=sa.BOOLEAN(),
               comment='True = não editável pelo tenant',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               comment='NULL = padrão do sistema',
               existing_nullable=True)

    with op.batch_alter_table('agricola_orcamento_itens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agricola_orcamento_itens_cultivo_id'))
        batch_op.drop_column('cultivo_id')

    op.create_table('agricola_produtos_colhidos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('safra_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('talhao_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('romaneio_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('commodity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('classificacao_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=False),
    sa.Column('unidade', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('peso_liquido_kg', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=False),
    sa.Column('umidade_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('impureza_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avariados_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('ardidos_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('quebrados_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('destino', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('armazem_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('data_entrada', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_saida_prevista', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('nf_origem', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dados_extras', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ARMAZENADO'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('cultivo_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['classificacao_id'], ['cadastros_commodities_classificacoes.id'], name=op.f('agricola_produtos_colhidos_classificacao_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['commodity_id'], ['cadastros_commodities.id'], name=op.f('agricola_produtos_colhidos_commodity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cultivo_id'], ['cultivos.id'], name=op.f('fk_agricola_produtos_colhidos_cultivo_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['romaneio_id'], ['romaneios_colheita.id'], name=op.f('agricola_produtos_colhidos_romaneio_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], name=op.f('agricola_produtos_colhidos_safra_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['cadastros_areas_rurais.id'], name=op.f('agricola_produtos_colhidos_talhao_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('agricola_produtos_colhidos_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agricola_produtos_colhidos_pkey'))
    )
    with op.batch_alter_table('agricola_produtos_colhidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agricola_produtos_colhidos_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agricola_produtos_colhidos_talhao_id'), ['talhao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agricola_produtos_colhidos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agricola_produtos_colhidos_safra_id'), ['safra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agricola_produtos_colhidos_romaneio_id'), ['romaneio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agricola_produtos_colhidos_commodity_id'), ['commodity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agricola_produtos_colhidos_classificacao_id'), ['classificacao_id'], unique=False)

    op.create_table('agricola_operacao_tipo_fase',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo_operacao', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment='Tipo de operação: PLANTIO, COLHEITA, PULVERIZAÇÃO, etc.'),
    sa.Column('fases_permitidas', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Lista de fases da safra permitidas: ["PLANTIO", "DESENVOLVIMENTO"]'),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True, comment='Descrição do tipo de operação'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agricola_operacao_tipo_fase_pkey'))
    )
    with op.batch_alter_table('agricola_operacao_tipo_fase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agricola_operacao_tipo_fase_tipo_operacao'), ['tipo_operacao'], unique=True)

    op.create_table('financeiro_comercializacoes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('numero_contrato', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('commodity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comprador_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=False),
    sa.Column('unidade', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('preco_unitario', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('moeda', sa.VARCHAR(length=3), server_default=sa.text("'BRL'::character varying"), autoincrement=False, nullable=False),
    sa.Column('valor_total', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('forma_pagamento', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('data_pagamento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_entrega_prevista', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_entrega_real', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('local_entrega', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('frete_por_conta', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('produto_colhido_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nf_numero', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nf_serie', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('nf_chave', sa.VARCHAR(length=44), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'RASCUNHO'::character varying"), autoincrement=False, nullable=False),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dados_extras', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('receita_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('criado_por', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commodity_id'], ['cadastros_commodities.id'], name=op.f('financeiro_comercializacoes_commodity_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['comprador_id'], ['cadastros_pessoas.id'], name=op.f('financeiro_comercializacoes_comprador_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_colhido_id'], ['agricola_produtos_colhidos.id'], name=op.f('financeiro_comercializacoes_produto_colhido_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('financeiro_comercializacoes_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('financeiro_comercializacoes_pkey'))
    )
    with op.batch_alter_table('financeiro_comercializacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financeiro_comercializacoes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financeiro_comercializacoes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_financeiro_comercializacoes_produto_colhido_id'), ['produto_colhido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financeiro_comercializacoes_numero_contrato'), ['numero_contrato'], unique=False)
        batch_op.create_index(batch_op.f('ix_financeiro_comercializacoes_comprador_id'), ['comprador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financeiro_comercializacoes_commodity_id'), ['commodity_id'], unique=False)

    op.create_table('caderno_campo_fotos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entrada_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
    sa.Column('data_captura', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['caderno_campo_entradas.id'], name=op.f('caderno_campo_fotos_entrada_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('caderno_campo_fotos_pkey'))
    )
    with op.batch_alter_table('caderno_campo_fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caderno_campo_fotos_entrada_id'), ['entrada_id'], unique=False)

    op.create_table('caderno_exportacoes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('safra_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('talhao_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('url_pdf', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('data_geracao', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('assinado_por', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('crea_rt', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('crea_validade', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('modelo_certificacao', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], name=op.f('caderno_exportacoes_safra_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('caderno_exportacoes_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('caderno_exportacoes_pkey'))
    )
    with op.batch_alter_table('caderno_exportacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caderno_exportacoes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_caderno_exportacoes_safra_id'), ['safra_id'], unique=False)

    op.create_table('epi_entregas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trabalhador_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('nome_trabalhador', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('epi_tipo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_entrega', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('validade', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('assinatura_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('operacao_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('epi_entregas_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('epi_entregas_pkey'))
    )
    with op.batch_alter_table('epi_entregas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epi_entregas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('caderno_campo_entradas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('safra_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('talhao_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data_registro', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('operacao_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_dispositivo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('excluida', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('motivo_exclusao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('digitalizacao_retroativa', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('justificativa_retroativa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nivel_severidade', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recomendacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('numero_receituario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes_agricolas.id'], name=op.f('caderno_campo_entradas_operacao_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], name=op.f('caderno_campo_entradas_safra_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['cadastros_areas_rurais.id'], name=op.f('caderno_campo_entradas_talhao_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('caderno_campo_entradas_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('caderno_campo_entradas_pkey'))
    )
    with op.batch_alter_table('caderno_campo_entradas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caderno_campo_entradas_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_caderno_campo_entradas_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_caderno_campo_entradas_talhao_id'), ['talhao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_caderno_campo_entradas_safra_id'), ['safra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_caderno_campo_entradas_data_registro'), ['data_registro'], unique=False)

    op.create_table('visitas_tecnicas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('safra_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('talhao_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('responsavel_tecnico_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome_rt', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('crea', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('data_visita', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recomendacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('constatacoes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('assinado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('data_assinatura', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], name=op.f('visitas_tecnicas_safra_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['cadastros_areas_rurais.id'], name=op.f('visitas_tecnicas_talhao_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('visitas_tecnicas_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('visitas_tecnicas_pkey'))
    )
    with op.batch_alter_table('visitas_tecnicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitas_tecnicas_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitas_tecnicas_talhao_id'), ['talhao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitas_tecnicas_safra_id'), ['safra_id'], unique=False)

    # ### end Alembic commands ###
