"""safra_talhoes_nn

Revision ID: 6f813e2a6f13
Revises: 08c865830c43
Create Date: 2026-03-27 17:02:36.821382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f813e2a6f13'
down_revision: Union[str, Sequence[str], None] = '08c865830c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safra_talhoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('area_ha', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['cadastros_areas_rurais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safra_talhoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safra_talhoes_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_talhoes_safra_id'), ['safra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_talhoes_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safra_talhoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safra_talhoes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_safra_talhoes_safra_id'))
        batch_op.drop_index(batch_op.f('ix_safra_talhoes_area_id'))

    op.drop_table('safra_talhoes')
    # ### end Alembic commands ###
