"""checklist_agricola_templates_itens

Revision ID: 7109d2ac3e9e
Revises: 7e48e8805cdd
Create Date: 2026-03-27 15:06:42.898914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7109d2ac3e9e'
down_revision: Union[str, Sequence[str], None] = '7e48e8805cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
