"""add_admin_models_and_fields

Revision ID: 7aec82540f16
Revises: 8dbcbab66821
Create Date: 2026-03-10 20:12:55.461493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aec82540f16'
down_revision: Union[str, Sequence[str], None] = '8dbcbab66821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados_suporte', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_chamado_atendente', 'usuarios', ['atendente_id'], ['id'])

    with op.batch_alter_table('frota_registros_manutencao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_frota_manutencao_os', 'frota_ordens_servico', ['os_id'], ['id'])

    with op.batch_alter_table('imoveis_rurais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geometria', sa.JSON(), nullable=True))

    with op.batch_alter_table('planos_assinatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tem_trial', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('dias_trial', sa.Integer(), nullable=False, server_default=sa.text('15')))
        batch_op.add_column(sa.Column('is_free', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('descricao_marketing', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('destaque', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('ordem', sa.Integer(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_usado_mb', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('storage_limite_mb', sa.Integer(), nullable=False, server_default=sa.text('10240')))
        batch_op.add_column(sa.Column('data_ultimo_acesso', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('email_responsavel', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telefone_responsavel', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('telefone_responsavel')
        batch_op.drop_column('email_responsavel')
        batch_op.drop_column('data_ultimo_acesso')
        batch_op.drop_column('storage_limite_mb')
        batch_op.drop_column('storage_usado_mb')

    with op.batch_alter_table('planos_assinatura', schema=None) as batch_op:
        batch_op.drop_column('ordem')
        batch_op.drop_column('destaque')
        batch_op.drop_column('descricao_marketing')
        batch_op.drop_column('is_free')
        batch_op.drop_column('dias_trial')
        batch_op.drop_column('tem_trial')

    with op.batch_alter_table('imoveis_rurais', schema=None) as batch_op:
        batch_op.drop_column('geometria')

    with op.batch_alter_table('frota_registros_manutencao', schema=None) as batch_op:
        batch_op.drop_constraint('fk_frota_manutencao_os', type_='foreignkey')
        batch_op.drop_column('os_id')

    with op.batch_alter_table('chamados_suporte', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chamado_atendente', type_='foreignkey')

    # ### end Alembic commands ###
