"""safra_ciclo_vida_fase_historico

Revision ID: 7e48e8805cdd
Revises: 1c6b9bf2f122
Create Date: 2026-03-27 14:55:21.490255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e48e8805cdd'
down_revision: Union[str, Sequence[str], None] = '1c6b9bf2f122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safra_fase_historico',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fase_anterior', sa.String(length=30), nullable=True),
    sa.Column('fase_nova', sa.String(length=30), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('dados_fase', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safra_fase_historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safra_fase_historico_safra_id'), ['safra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_fase_historico_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('frota_abastecimentos', schema=None) as batch_op:
        batch_op.alter_column('fornecedor_id',
               existing_type=sa.UUID(),
               comment='Fornecedor do combustível (quando abastecimento externo)',
               existing_comment='FK lógica para pessoas/fornecedores',
               existing_nullable=True)

    with op.batch_alter_table('frota_apontamentos_uso', schema=None) as batch_op:
        batch_op.alter_column('talhao_id',
               existing_type=sa.UUID(),
               comment='Talhão onde a operação foi realizada',
               existing_comment='FK lógica para talhoes.id',
               existing_nullable=True)
        batch_op.alter_column('operacao_id',
               existing_type=sa.UUID(),
               comment='Tipo de operação realizada (plantio, pulverização, etc)',
               existing_comment='FK lógica para operacoes.id',
               existing_nullable=True)

    with op.batch_alter_table('operacoes_agricolas', schema=None) as batch_op:
        batch_op.alter_column('operador_id',
               existing_type=sa.UUID(),
               comment='Operador que realizou a operação agrícola',
               existing_nullable=True)

    with op.batch_alter_table('rh_empreitadas', schema=None) as batch_op:
        batch_op.alter_column('safra_id',
               existing_type=sa.UUID(),
               comment='Safra à qual a empreitada está vinculada',
               existing_nullable=True)

    with op.batch_alter_table('rh_lancamentos_diarias', schema=None) as batch_op:
        batch_op.alter_column('safra_id',
               existing_type=sa.UUID(),
               comment='Safra à qual o lançamento está vinculado',
               existing_nullable=True)

    with op.batch_alter_table('romaneios_colheita', schema=None) as batch_op:
        batch_op.alter_column('operador_id',
               existing_type=sa.UUID(),
               comment='Operador da colhedora',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('romaneios_colheita', schema=None) as batch_op:
        batch_op.alter_column('operador_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Operador da colhedora',
               existing_nullable=True)

    with op.batch_alter_table('rh_lancamentos_diarias', schema=None) as batch_op:
        batch_op.alter_column('safra_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Safra à qual o lançamento está vinculado',
               existing_nullable=True)

    with op.batch_alter_table('rh_empreitadas', schema=None) as batch_op:
        batch_op.alter_column('safra_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Safra à qual a empreitada está vinculada',
               existing_nullable=True)

    with op.batch_alter_table('operacoes_agricolas', schema=None) as batch_op:
        batch_op.alter_column('operador_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Operador que realizou a operação agrícola',
               existing_nullable=True)

    with op.batch_alter_table('frota_apontamentos_uso', schema=None) as batch_op:
        batch_op.alter_column('operacao_id',
               existing_type=sa.UUID(),
               comment='FK lógica para operacoes.id',
               existing_comment='Tipo de operação realizada (plantio, pulverização, etc)',
               existing_nullable=True)
        batch_op.alter_column('talhao_id',
               existing_type=sa.UUID(),
               comment='FK lógica para talhoes.id',
               existing_comment='Talhão onde a operação foi realizada',
               existing_nullable=True)

    with op.batch_alter_table('frota_abastecimentos', schema=None) as batch_op:
        batch_op.alter_column('fornecedor_id',
               existing_type=sa.UUID(),
               comment='FK lógica para pessoas/fornecedores',
               existing_comment='Fornecedor do combustível (quando abastecimento externo)',
               existing_nullable=True)

    with op.batch_alter_table('safra_fase_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safra_fase_historico_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_safra_fase_historico_safra_id'))

    op.drop_table('safra_fase_historico')
    # ### end Alembic commands ###
