"""add crm tables

Revision ID: 8801a990eb5d
Revises: a1b2c3d4e5f6
Create Date: 2026-03-22 19:31:40.895302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8801a990eb5d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_pipeline_estagios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('estagio_id', sa.Uuid(), nullable=False),
    sa.Column('origem', sa.String(length=50), nullable=False, comment='manual, site, indicacao, evento, social, parceiro'),
    sa.Column('valor_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('plano_interesse', sa.String(length=100), nullable=True),
    sa.Column('qtd_fazendas', sa.Integer(), nullable=True),
    sa.Column('qtd_usuarios', sa.Integer(), nullable=True),
    sa.Column('responsavel_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ativo, convertido, perdido'),
    sa.Column('motivo_perda', sa.Text(), nullable=True),
    sa.Column('data_conversao', sa.Date(), nullable=True),
    sa.Column('tenant_convertido_id', sa.Uuid(), nullable=True, comment='ID do tenant criado após conversão'),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estagio_id'], ['crm_pipeline_estagios.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_leads_estagio_id'), ['estagio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_leads_responsavel_id'), ['responsavel_id'], unique=False)

    op.create_table('crm_atividades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False, comment='ligacao, email, reuniao, nota, tarefa, whatsapp'),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_agendada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluida', sa.Boolean(), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_atividades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_atividades_lead_id'), ['lead_id'], unique=False)

    op.create_table('admin_impersonations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=True, comment='Fazenda específica sendo acessada (NULL = contexto geral do tenant)'),
    sa.Column('motivo', sa.Text(), nullable=False, comment="Motivo do acesso (ex: 'Suporte técnico - configuração SMTP')"),
    sa.Column('categoria', sa.String(length=50), nullable=False, comment='SUPORTE, AUDITORIA, DEMONSTRACAO, MIGRACAO, EMERGENCIA'),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False, comment='Início da sessão de impersonation'),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=True, comment='Fim da sessão (NULL = ainda ativa)'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP do admin durante o acesso'),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('acoes_realizadas', sa.JSON(), nullable=False, comment='\n        Array de objetos com as ações realizadas:\n        [{\n            "timestamp": "2024-03-12T10:30:00Z",\n            "acao": "UPDATE",\n            "recurso": "configuracoes.smtp",\n            "detalhes": {"campo": "smtp_host", "valor_anterior": "...", "valor_novo": "..."}\n        }]\n        '),
    sa.Column('meta_info', sa.JSON(), nullable=True, comment='Informações adicionais (ticket de suporte, aprovação, etc)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_impersonations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_impersonations_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_impersonations_inicio'), ['inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_impersonations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sessoes_ativas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('grupo_fazendas_id', sa.Uuid(), nullable=True, comment='Grupo ao qual a sessão pertence (para limite compartilhado)'),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=True, comment='Fazenda ativa na sessão (pode mudar sem encerrar a sessão)'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='Hash SHA256 do JWT para identificação única da sessão'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='Endereço IP do cliente'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User agent do navegador/app'),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False, comment='Data/hora de início da sessão'),
    sa.Column('ultimo_heartbeat', sa.DateTime(timezone=True), nullable=False, comment='Última atividade do usuário (atualizado a cada requisição)'),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False, comment='Data/hora de expiração da sessão (inicio + 30min de inatividade)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ATIVA (em uso), EXPIRADA (timeout), ENCERRADA (logout manual)'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grupo_fazendas_id'], ['grupos_fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessoes_ativas', schema=None) as batch_op:
        batch_op.create_index('idx_sessoes_limite_grupo', ['tenant_id', 'grupo_fazendas_id', 'status', 'expira_em'], unique=False)
        batch_op.create_index('idx_sessoes_limpeza', ['status', 'expira_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_ativas_expira_em'), ['expira_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_ativas_grupo_fazendas_id'), ['grupo_fazendas_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_ativas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_ativas_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_ativas_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessoes_ativas_ultimo_heartbeat'), ['ultimo_heartbeat'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_ativas_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('assinaturas_tenant', schema=None) as batch_op:
        batch_op.alter_column('usuarios_contratados',
               existing_type=sa.INTEGER(),
               comment='Quantidade de usuários simultâneos contratados',
               existing_nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('data_bloqueio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data do último bloqueio',
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('assinaturas_tenant_tenant_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_assinaturas_tenant_grupo_fazendas_id'), ['grupo_fazendas_id'], unique=False)

    with op.batch_alter_table('cobrancas_asaas', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               comment='PENDING, RECEIVED, CONFIRMED, OVERDUE, REFUNDED, RECEIVED_IN_CASH, REFUND_REQUESTED, CHARGEBACK_REQUESTED, CHARGEBACK_DISPUTE, AWAITING_CHARGEBACK_REVERSAL, DUNNING_REQUESTED, DUNNING_RECEIVED, AWAITING_RISK_ANALYSIS',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('cobrancas_asaas_asaas_charge_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_cobrancas_asaas_asaas_charge_id'))
        batch_op.create_index(batch_op.f('ix_cobrancas_asaas_asaas_charge_id'), ['asaas_charge_id'], unique=True)

    with op.batch_alter_table('fazenda_usuarios', schema=None) as batch_op:
        batch_op.alter_column('perfil_fazenda_id',
               existing_type=sa.UUID(),
               comment='Se NULL, usa o perfil do TenantUsuario. Se preenchido, sobrescreve para esta fazenda.',
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fazenda_usuarios_perfil_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'perfis_acesso', ['perfil_fazenda_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fazendas', schema=None) as batch_op:
        batch_op.alter_column('grupo_id',
               existing_type=sa.UUID(),
               comment='Grupo ao qual esta fazenda pertence (NULL = sem grupo)',
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fazendas_grupo_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'grupos_fazendas', ['grupo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('grupos_fazendas', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               comment="Ex: 'Fazendas Região Sul', 'Unidades Pecuária'",
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               comment='Descrição detalhada do grupo',
               existing_nullable=True)
        batch_op.alter_column('cor',
               existing_type=sa.VARCHAR(length=7),
               comment="Cor HEX para identificação visual (ex: '#3B82F6')",
               existing_nullable=True)
        batch_op.alter_column('icone',
               existing_type=sa.VARCHAR(length=50),
               comment="Nome do ícone para UI (ex: 'MapPin', 'Building2')",
               existing_nullable=True)
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Ordem de exibição na listagem',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Grupos inativos são ocultados mas mantém histórico',
               existing_server_default=sa.text('true'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('historico_bloqueios', schema=None) as batch_op:
        batch_op.alter_column('motivo',
               existing_type=sa.VARCHAR(length=50),
               comment='INADIMPLENCIA_MUDANCA_PLANO, INADIMPLENCIA_MENSALIDADE, VIOLACAO_TERMOS, MANUAL',
               existing_nullable=False)
        batch_op.alter_column('bloqueado_automaticamente',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('mudancas_plano', schema=None) as batch_op:
        batch_op.alter_column('tipo_mudanca',
               existing_type=sa.VARCHAR(length=30),
               comment='UPGRADE_PLANO, DOWNGRADE_PLANO, UPGRADE_USUARIOS, DOWNGRADE_USUARIOS, UPGRADE_COMPLETO, DOWNGRADE_COMPLETO',
               existing_nullable=False)
        batch_op.alter_column('valor_calculado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Valor a ser cobrado (upgrade) ou creditado (downgrade futuro)',
               existing_nullable=False)
        batch_op.alter_column('valor_proporcional',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Valor proporcional aos dias restantes do ciclo',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               comment='pendente_pagamento, liberado_manualmente, pago, aplicado, bloqueado, cancelado',
               existing_nullable=False,
               existing_server_default=sa.text("'pendente_pagamento'::character varying"))
        batch_op.alter_column('liberado_manualmente',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('data_limite_pagamento',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Prazo para regularizar pagamento em caso de liberação manual',
               existing_nullable=True)
        batch_op.alter_column('aplicado_por_job',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('agendado_para',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Data de aplicação agendada (usado em downgrades)',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('mudancas_plano_cobranca_asaas_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_mudancas_plano_cobranca_asaas_id'))
        batch_op.create_index(batch_op.f('ix_mudancas_plano_cobranca_asaas_id'), ['cobranca_asaas_id'], unique=True)

    with op.batch_alter_table('plano_pricing', schema=None) as batch_op:
        batch_op.alter_column('faixa_inicio',
               existing_type=sa.INTEGER(),
               comment='Início da faixa (inclusivo)',
               existing_nullable=False)
        batch_op.alter_column('faixa_fim',
               existing_type=sa.INTEGER(),
               comment='Fim da faixa (inclusivo). NULL = ilimitado',
               existing_nullable=True)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('planos_assinatura', schema=None) as batch_op:
        batch_op.alter_column('limite_usuarios_minimo',
               existing_type=sa.INTEGER(),
               comment='Quantidade mínima de usuários para este plano',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('limite_usuarios_maximo',
               existing_type=sa.INTEGER(),
               comment='Quantidade máxima de usuários. NULL = ilimitado',
               existing_nullable=True)
        batch_op.alter_column('limite_usuarios',
               existing_type=sa.INTEGER(),
               comment='DEPRECATED: valor de referência apenas',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos_assinatura', schema=None) as batch_op:
        batch_op.alter_column('limite_usuarios',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='DEPRECATED: valor de referência apenas',
               existing_nullable=False)
        batch_op.alter_column('limite_usuarios_maximo',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantidade máxima de usuários. NULL = ilimitado',
               existing_nullable=True)
        batch_op.alter_column('limite_usuarios_minimo',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantidade mínima de usuários para este plano',
               existing_nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('plano_pricing', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('faixa_fim',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Fim da faixa (inclusivo). NULL = ilimitado',
               existing_nullable=True)
        batch_op.alter_column('faixa_inicio',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Início da faixa (inclusivo)',
               existing_nullable=False)

    with op.batch_alter_table('mudancas_plano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mudancas_plano_cobranca_asaas_id'))
        batch_op.create_index(batch_op.f('ix_mudancas_plano_cobranca_asaas_id'), ['cobranca_asaas_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('mudancas_plano_cobranca_asaas_id_key'), ['cobranca_asaas_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('agendado_para',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data de aplicação agendada (usado em downgrades)',
               existing_nullable=True)
        batch_op.alter_column('aplicado_por_job',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('data_limite_pagamento',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Prazo para regularizar pagamento em caso de liberação manual',
               existing_nullable=True)
        batch_op.alter_column('liberado_manualmente',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='pendente_pagamento, liberado_manualmente, pago, aplicado, bloqueado, cancelado',
               existing_nullable=False,
               existing_server_default=sa.text("'pendente_pagamento'::character varying"))
        batch_op.alter_column('valor_proporcional',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Valor proporcional aos dias restantes do ciclo',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('valor_calculado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Valor a ser cobrado (upgrade) ou creditado (downgrade futuro)',
               existing_nullable=False)
        batch_op.alter_column('tipo_mudanca',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='UPGRADE_PLANO, DOWNGRADE_PLANO, UPGRADE_USUARIOS, DOWNGRADE_USUARIOS, UPGRADE_COMPLETO, DOWNGRADE_COMPLETO',
               existing_nullable=False)

    with op.batch_alter_table('historico_bloqueios', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('bloqueado_automaticamente',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('motivo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='INADIMPLENCIA_MUDANCA_PLANO, INADIMPLENCIA_MENSALIDADE, VIOLACAO_TERMOS, MANUAL',
               existing_nullable=False)

    with op.batch_alter_table('grupos_fazendas', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Grupos inativos são ocultados mas mantém histórico',
               existing_server_default=sa.text('true'))
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Ordem de exibição na listagem',
               existing_server_default=sa.text('0'))
        batch_op.alter_column('icone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Nome do ícone para UI (ex: 'MapPin', 'Building2')",
               existing_nullable=True)
        batch_op.alter_column('cor',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment="Cor HEX para identificação visual (ex: '#3B82F6')",
               existing_nullable=True)
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descrição detalhada do grupo',
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment="Ex: 'Fazendas Região Sul', 'Unidades Pecuária'",
               existing_nullable=False)

    with op.batch_alter_table('fazendas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fazendas_grupo_id_fkey'), 'grupos_fazendas', ['grupo_id'], ['id'])
        batch_op.alter_column('grupo_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Grupo ao qual esta fazenda pertence (NULL = sem grupo)',
               existing_nullable=True)

    with op.batch_alter_table('fazenda_usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fazenda_usuarios_perfil_fazenda_id_fkey'), 'perfis_acesso', ['perfil_fazenda_id'], ['id'])
        batch_op.alter_column('perfil_fazenda_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Se NULL, usa o perfil do TenantUsuario. Se preenchido, sobrescreve para esta fazenda.',
               existing_nullable=True)

    with op.batch_alter_table('cobrancas_asaas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cobrancas_asaas_asaas_charge_id'))
        batch_op.create_index(batch_op.f('ix_cobrancas_asaas_asaas_charge_id'), ['asaas_charge_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('cobrancas_asaas_asaas_charge_id_key'), ['asaas_charge_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='PENDING, RECEIVED, CONFIRMED, OVERDUE, REFUNDED, RECEIVED_IN_CASH, REFUND_REQUESTED, CHARGEBACK_REQUESTED, CHARGEBACK_DISPUTE, AWAITING_CHARGEBACK_REVERSAL, DUNNING_REQUESTED, DUNNING_RECEIVED, AWAITING_RISK_ANALYSIS',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))

    with op.batch_alter_table('assinaturas_tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assinaturas_tenant_grupo_fazendas_id'))
        batch_op.create_unique_constraint(batch_op.f('assinaturas_tenant_tenant_id_key'), ['tenant_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('data_bloqueio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Data do último bloqueio',
               existing_nullable=True)
        batch_op.alter_column('usuarios_contratados',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Quantidade de usuários simultâneos contratados',
               existing_nullable=False,
               existing_server_default=sa.text('5'))

    with op.batch_alter_table('sessoes_ativas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessoes_ativas_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_sessoes_ativas_ultimo_heartbeat'))
        batch_op.drop_index(batch_op.f('ix_sessoes_ativas_token_hash'))
        batch_op.drop_index(batch_op.f('ix_sessoes_ativas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sessoes_ativas_status'))
        batch_op.drop_index(batch_op.f('ix_sessoes_ativas_grupo_fazendas_id'))
        batch_op.drop_index(batch_op.f('ix_sessoes_ativas_expira_em'))
        batch_op.drop_index('idx_sessoes_limpeza')
        batch_op.drop_index('idx_sessoes_limite_grupo')

    op.drop_table('sessoes_ativas')
    with op.batch_alter_table('admin_impersonations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_impersonations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_admin_impersonations_inicio'))
        batch_op.drop_index(batch_op.f('ix_admin_impersonations_admin_user_id'))

    op.drop_table('admin_impersonations')
    with op.batch_alter_table('crm_atividades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_atividades_lead_id'))

    op.drop_table('crm_atividades')
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_leads_responsavel_id'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_nome'))
        batch_op.drop_index(batch_op.f('ix_crm_leads_estagio_id'))

    op.drop_table('crm_leads')
    op.drop_table('crm_pipeline_estagios')
    # ### end Alembic commands ###
