"""caderno_campo

Revision ID: 8c2e891d6ba9
Revises: 86940627be53
Create Date: 2026-04-06 03:07:16.569599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c2e891d6ba9'
down_revision: Union[str, Sequence[str], None] = '86940627be53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescricoes_vra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescricoes_vra_id'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_vra_tenant_id'))

    op.drop_table('prescricoes_vra')
    with op.batch_alter_table('cadastros_areas_rurais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_areas_rurais_talhao_fazenda'), postgresql_where="((tipo)::text = 'TALHAO'::text)")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_areas_rurais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_areas_rurais_talhao_fazenda'), ['fazenda_id', 'tipo'], unique=False, postgresql_where="((tipo)::text = 'TALHAO'::text)")

    op.create_table('prescricoes_vra',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('talhao_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('safra_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('elemento', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dose_media', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dose_minima', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dose_maxima', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unidade', sa.VARCHAR(length=20), server_default=sa.text("'kg/ha'::character varying"), autoincrement=False, nullable=True),
    sa.Column('caminho_isoxml', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('caminho_shapefile', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('caminho_geojson', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('grid_tamanho_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_pontos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'rascunho'::character varying"), autoincrement=False, nullable=True),
    sa.Column('aprovada_por', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('aprovada_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('responsavel_tecnico', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('crt', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criada_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('atualizada_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], name=op.f('prescricoes_vra_fazenda_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], name=op.f('prescricoes_vra_safra_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['talhao_id'], ['cadastros_areas_rurais.id'], name=op.f('prescricoes_vra_talhao_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('prescricoes_vra_pkey'))
    )
    with op.batch_alter_table('prescricoes_vra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescricoes_vra_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_vra_id'), ['id'], unique=False)

    # ### end Alembic commands ###
