"""clean_sqlite_compat

Revision ID: 8dbcbab66821
Revises: 
Create Date: 2026-03-07 22:11:32.684898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbcbab66821'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culturas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nome_cientifico', sa.String(length=150), nullable=True),
    sa.Column('variedade', sa.String(length=100), nullable=True),
    sa.Column('ciclo_dias', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_culturas_tenant_id'), 'culturas', ['tenant_id'], unique=False)
    op.create_table('talhoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('area_ha', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('area_ha_manual', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('geometria', sa.JSON(), nullable=True),
    sa.Column('centroide', sa.JSON(), nullable=True),
    sa.Column('tipo_solo', sa.String(length=50), nullable=True),
    sa.Column('classe_solo', sa.String(length=10), nullable=True),
    sa.Column('textura_solo', sa.String(length=20), nullable=True),
    sa.Column('relevo', sa.String(length=20), nullable=True),
    sa.Column('irrigado', sa.Boolean(), nullable=False),
    sa.Column('sistema_irrigacao', sa.String(length=50), nullable=True),
    sa.Column('historico_culturas', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talhoes_tenant_id'), 'talhoes', ['tenant_id'], unique=False)
    op.create_table('safras',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('ano_safra', sa.String(length=10), nullable=False),
    sa.Column('cultura', sa.String(length=50), nullable=False),
    sa.Column('cultivar_id', sa.Uuid(), nullable=True),
    sa.Column('cultivar_nome', sa.String(length=100), nullable=True),
    sa.Column('sistema_plantio', sa.String(length=30), nullable=True),
    sa.Column('data_plantio_prevista', sa.Date(), nullable=True),
    sa.Column('data_plantio_real', sa.Date(), nullable=True),
    sa.Column('data_colheita_prevista', sa.Date(), nullable=True),
    sa.Column('data_colheita_real', sa.Date(), nullable=True),
    sa.Column('populacao_prevista', sa.Integer(), nullable=True),
    sa.Column('populacao_real', sa.Integer(), nullable=True),
    sa.Column('espacamento_cm', sa.Integer(), nullable=True),
    sa.Column('area_plantada_ha', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('produtividade_meta_sc_ha', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('produtividade_real_sc_ha', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('preco_venda_previsto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('custo_previsto_ha', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('custo_realizado_ha', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cultivar_id'], ['culturas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['talhao_id'], ['talhoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safras_talhao_id'), 'safras', ['talhao_id'], unique=False)
    op.create_index(op.f('ix_safras_tenant_id'), 'safras', ['tenant_id'], unique=False)
    op.create_table('monitoramento_pragas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('data_avaliacao', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('nome_cientifico', sa.String(length=100), nullable=True),
    sa.Column('nome_popular', sa.String(length=100), nullable=True),
    sa.Column('nivel_infestacao', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('unidade_medida', sa.String(length=30), nullable=True),
    sa.Column('nde_cultura', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('atingiu_nde', sa.Boolean(), nullable=False),
    sa.Column('fotos', sa.JSON(), nullable=False),
    sa.Column('pontos_coleta', sa.JSON(), nullable=True),
    sa.Column('diagnostico_ia', sa.JSON(), nullable=True),
    sa.Column('tecnico_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['talhoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoramento_pragas_safra_id'), 'monitoramento_pragas', ['safra_id'], unique=False)
    op.create_index(op.f('ix_monitoramento_pragas_talhao_id'), 'monitoramento_pragas', ['talhao_id'], unique=False)
    op.create_index(op.f('ix_monitoramento_pragas_tenant_id'), 'monitoramento_pragas', ['tenant_id'], unique=False)
    op.create_table('operacoes_agricolas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('subtipo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('data_realizada', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('area_aplicada_ha', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('maquina_id', sa.Uuid(), nullable=True),
    sa.Column('implemento', sa.String(length=100), nullable=True),
    sa.Column('operador_id', sa.Uuid(), nullable=True),
    sa.Column('temperatura_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('umidade_rel', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vento_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('direcao_vento', sa.String(length=10), nullable=True),
    sa.Column('condicao_clima', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('custo_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('custo_por_ha', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('fotos', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['talhoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operacoes_agricolas_safra_id'), 'operacoes_agricolas', ['safra_id'], unique=False)
    op.create_index(op.f('ix_operacoes_agricolas_talhao_id'), 'operacoes_agricolas', ['talhao_id'], unique=False)
    op.create_index(op.f('ix_operacoes_agricolas_tenant_id'), 'operacoes_agricolas', ['tenant_id'], unique=False)
    op.create_table('previsoes_produtividade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('data_previsao', sa.Date(), nullable=False),
    sa.Column('produtividade_estimada_sc_ha', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('margem_erro_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fatores_peso', sa.JSON(), nullable=True),
    sa.Column('historico_clima', sa.JSON(), nullable=True),
    sa.Column('indice_ndvi_medio', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('modelo_ia_versao', sa.String(length=50), nullable=True),
    sa.Column('run_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['talhoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_previsoes_produtividade_safra_id'), 'previsoes_produtividade', ['safra_id'], unique=False)
    op.create_index(op.f('ix_previsoes_produtividade_talhao_id'), 'previsoes_produtividade', ['talhao_id'], unique=False)
    op.create_index(op.f('ix_previsoes_produtividade_tenant_id'), 'previsoes_produtividade', ['tenant_id'], unique=False)
    op.create_table('romaneios_colheita',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('numero_romaneio', sa.String(length=30), nullable=True),
    sa.Column('data_colheita', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=True),
    sa.Column('maquina_colhedora_id', sa.Uuid(), nullable=True),
    sa.Column('operador_id', sa.Uuid(), nullable=True),
    sa.Column('peso_bruto_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('tara_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('peso_liquido_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('umidade_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('impureza_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avariados_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('desconto_umidade_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('desconto_impureza_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('peso_liquido_padrao_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('sacas_60kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('destino', sa.String(length=30), nullable=True),
    sa.Column('armazem_id', sa.Uuid(), nullable=True),
    sa.Column('nf_id', sa.Uuid(), nullable=True),
    sa.Column('preco_saca', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('receita_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['talhoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_romaneios_colheita_safra_id'), 'romaneios_colheita', ['safra_id'], unique=False)
    op.create_index(op.f('ix_romaneios_colheita_talhao_id'), 'romaneios_colheita', ['talhao_id'], unique=False)
    op.create_index(op.f('ix_romaneios_colheita_tenant_id'), 'romaneios_colheita', ['tenant_id'], unique=False)
    op.create_table('insumos_operacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operacao_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('insumo_id', sa.Uuid(), nullable=False),
    sa.Column('lote_insumo', sa.String(length=50), nullable=True),
    sa.Column('dose_por_ha', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('area_aplicada', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('quantidade_total', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('custo_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('carencia_dias', sa.Numeric(precision=4, scale=0), nullable=True),
    sa.Column('data_reentrada', sa.Date(), nullable=True),
    sa.Column('epi_necessario', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes_agricolas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insumos_operacao')
    op.drop_index(op.f('ix_romaneios_colheita_tenant_id'), table_name='romaneios_colheita')
    op.drop_index(op.f('ix_romaneios_colheita_talhao_id'), table_name='romaneios_colheita')
    op.drop_index(op.f('ix_romaneios_colheita_safra_id'), table_name='romaneios_colheita')
    op.drop_table('romaneios_colheita')
    op.drop_index(op.f('ix_previsoes_produtividade_tenant_id'), table_name='previsoes_produtividade')
    op.drop_index(op.f('ix_previsoes_produtividade_talhao_id'), table_name='previsoes_produtividade')
    op.drop_index(op.f('ix_previsoes_produtividade_safra_id'), table_name='previsoes_produtividade')
    op.drop_table('previsoes_produtividade')
    op.drop_index(op.f('ix_operacoes_agricolas_tenant_id'), table_name='operacoes_agricolas')
    op.drop_index(op.f('ix_operacoes_agricolas_talhao_id'), table_name='operacoes_agricolas')
    op.drop_index(op.f('ix_operacoes_agricolas_safra_id'), table_name='operacoes_agricolas')
    op.drop_table('operacoes_agricolas')
    op.drop_index(op.f('ix_monitoramento_pragas_tenant_id'), table_name='monitoramento_pragas')
    op.drop_index(op.f('ix_monitoramento_pragas_talhao_id'), table_name='monitoramento_pragas')
    op.drop_index(op.f('ix_monitoramento_pragas_safra_id'), table_name='monitoramento_pragas')
    op.drop_table('monitoramento_pragas')
    op.drop_index(op.f('ix_safras_tenant_id'), table_name='safras')
    op.drop_index(op.f('ix_safras_talhao_id'), table_name='safras')
    op.drop_table('safras')
    op.drop_index(op.f('ix_talhoes_tenant_id'), table_name='talhoes')
    op.drop_table('talhoes')
    op.drop_index(op.f('ix_culturas_tenant_id'), table_name='culturas')
    op.drop_table('culturas')
    # ### end Alembic commands ###
