"""remove_area_aproveitavel_ha_from_unidades_produtivas

Revision ID: 9069070a48f7
Revises: c853a6f175f1
Create Date: 2026-04-10 15:02:11.054252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9069070a48f7'
down_revision: Union[str, Sequence[str], None] = 'c853a6f175f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades_produtivas', schema=None) as batch_op:
        batch_op.alter_column('area_app_ha',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='Área de Preservação Permanente — referência inicial, calculada via polígonos APP',
               existing_comment='Área de Preservação Permanente',
               existing_nullable=True)
        batch_op.alter_column('area_rl_ha',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='Área de Reserva Legal — referência inicial, calculada via polígonos RL',
               existing_comment='Área de Reserva Legal',
               existing_nullable=True)
        batch_op.drop_column('area_aproveitavel_ha')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades_produtivas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_aproveitavel_ha', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
        batch_op.alter_column('area_rl_ha',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='Área de Reserva Legal',
               existing_comment='Área de Reserva Legal — referência inicial, calculada via polígonos RL',
               existing_nullable=True)
        batch_op.alter_column('area_app_ha',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='Área de Preservação Permanente',
               existing_comment='Área de Preservação Permanente — referência inicial, calculada via polígonos APP',
               existing_nullable=True)

    # ### end Alembic commands ###
