"""frota_apontamento_abastecimento_checklist_documentos

Revision ID: 9be54904b80e
Revises: f247473aa254
Create Date: 2026-03-25 22:35:15.902363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be54904b80e'
down_revision: Union[str, Sequence[str], None] = 'f247473aa254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frota_checklist_modelos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo_equipamento', sa.String(length=30), nullable=True, comment='Tipo de equipamento alvo (TRATOR, COLHEDORA…); NULL = genérico'),
    sa.Column('itens', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frota_checklist_modelos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frota_checklist_modelos_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_checklist_modelos_tipo_equipamento'), ['tipo_equipamento'], unique=False)

    op.create_table('cadastros_areas_valores_patrimoniais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('data_avaliacao', sa.DateTime(timezone=True), nullable=False, comment='Data de referência desta avaliação'),
    sa.Column('metodo', sa.String(length=20), nullable=False, comment='Método de avaliação utilizado'),
    sa.Column('valor_terra_nua', sa.Float(), nullable=True, comment='Valor da terra sem benfeitorias (base ITR/INCRA)'),
    sa.Column('valor_benfeitorias', sa.Float(), nullable=True, comment='Valor de construções, silos, cercas, infraestrutura'),
    sa.Column('valor_lavoura_perene', sa.Float(), nullable=True, comment='Valor de culturas perenes (laranjal, canavial, etc.)'),
    sa.Column('valor_total', sa.Float(), nullable=True, comment='Valor total consolidado (pode ser soma ou valor independente)'),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('responsavel', sa.String(length=200), nullable=True, comment='Avaliador ou responsável pelo laudo'),
    sa.Column('numero_laudo', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['cadastros_areas_rurais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_areas_valores_patrimoniais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_areas_valores_patrimoniais_area_id'), ['area_id'], unique=False)

    op.create_table('frota_abastecimentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('equipamento_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operador_id', sa.Uuid(), nullable=True),
    sa.Column('horimetro_na_data', sa.Float(), nullable=False),
    sa.Column('km_na_data', sa.Float(), nullable=True),
    sa.Column('tipo_combustivel', sa.String(length=20), nullable=False),
    sa.Column('litros', sa.Float(), nullable=False),
    sa.Column('preco_litro', sa.Float(), nullable=False),
    sa.Column('custo_total', sa.Float(), nullable=False),
    sa.Column('tanque_cheio', sa.Boolean(), nullable=False),
    sa.Column('local', sa.String(length=20), nullable=False),
    sa.Column('fornecedor_id', sa.Uuid(), nullable=True, comment='FK lógica para pessoas/fornecedores'),
    sa.Column('nota_fiscal', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['cadastros_equipamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operador_id'], ['cadastros_pessoas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frota_abastecimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frota_abastecimentos_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_abastecimentos_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_abastecimentos_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('frota_apontamentos_uso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('equipamento_id', sa.Uuid(), nullable=False),
    sa.Column('operador_id', sa.Uuid(), nullable=True),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('horimetro_inicio', sa.Float(), nullable=False),
    sa.Column('horimetro_fim', sa.Float(), nullable=False),
    sa.Column('km_inicio', sa.Float(), nullable=True),
    sa.Column('km_fim', sa.Float(), nullable=True),
    sa.Column('fazenda_id', sa.Uuid(), nullable=True),
    sa.Column('talhao_id', sa.Uuid(), nullable=True, comment='FK lógica para talhoes.id'),
    sa.Column('operacao_id', sa.Uuid(), nullable=True, comment='FK lógica para operacoes.id'),
    sa.Column('implementos_ids', sa.JSON(), nullable=True, comment='Lista de UUIDs de implementos acoplados no turno'),
    sa.Column('combustivel_consumido_l', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['cadastros_equipamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operador_id'], ['cadastros_pessoas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frota_apontamentos_uso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frota_apontamentos_uso_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_apontamentos_uso_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_apontamentos_uso_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('frota_documentos_equipamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('equipamento_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=100), nullable=True, comment='Número do documento'),
    sa.Column('orgao_emissor', sa.String(length=100), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('arquivo_url', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['cadastros_equipamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frota_documentos_equipamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frota_documentos_equipamentos_data_vencimento'), ['data_vencimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_documentos_equipamentos_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_documentos_equipamentos_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_documentos_equipamentos_tipo'), ['tipo'], unique=False)

    op.create_table('frota_checklists_realizados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('equipamento_id', sa.Uuid(), nullable=False),
    sa.Column('modelo_id', sa.Uuid(), nullable=False),
    sa.Column('operador_id', sa.Uuid(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('respostas', sa.JSON(), nullable=False),
    sa.Column('liberado_para_uso', sa.Boolean(), nullable=False),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.Column('os_gerada_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['cadastros_equipamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modelo_id'], ['frota_checklist_modelos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operador_id'], ['cadastros_pessoas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['os_gerada_id'], ['frota_ordens_servico.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frota_checklists_realizados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frota_checklists_realizados_data_hora'), ['data_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_checklists_realizados_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_checklists_realizados_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('cadastros_areas_matriculas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('livro', sa.String(length=50), nullable=True, comment='Livro do registro cartorial'))
        batch_op.add_column(sa.Column('folha', sa.String(length=50), nullable=True, comment='Folha do registro cartorial'))
        batch_op.add_column(sa.Column('data_registro', sa.DateTime(timezone=True), nullable=True, comment='Data do registro em cartório'))
        batch_op.add_column(sa.Column('sncr', sa.String(length=30), nullable=True, comment='Sistema Nacional de Cadastro Rural (INCRA)'))
        batch_op.add_column(sa.Column('itr_numero', sa.String(length=50), nullable=True, comment='Número do processo ITR na Receita Federal'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_areas_matriculas', schema=None) as batch_op:
        batch_op.drop_column('itr_numero')
        batch_op.drop_column('sncr')
        batch_op.drop_column('data_registro')
        batch_op.drop_column('folha')
        batch_op.drop_column('livro')

    with op.batch_alter_table('frota_checklists_realizados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frota_checklists_realizados_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_frota_checklists_realizados_equipamento_id'))
        batch_op.drop_index(batch_op.f('ix_frota_checklists_realizados_data_hora'))

    op.drop_table('frota_checklists_realizados')
    with op.batch_alter_table('frota_documentos_equipamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frota_documentos_equipamentos_tipo'))
        batch_op.drop_index(batch_op.f('ix_frota_documentos_equipamentos_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_frota_documentos_equipamentos_equipamento_id'))
        batch_op.drop_index(batch_op.f('ix_frota_documentos_equipamentos_data_vencimento'))

    op.drop_table('frota_documentos_equipamentos')
    with op.batch_alter_table('frota_apontamentos_uso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frota_apontamentos_uso_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_frota_apontamentos_uso_equipamento_id'))
        batch_op.drop_index(batch_op.f('ix_frota_apontamentos_uso_data'))

    op.drop_table('frota_apontamentos_uso')
    with op.batch_alter_table('frota_abastecimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frota_abastecimentos_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_frota_abastecimentos_equipamento_id'))
        batch_op.drop_index(batch_op.f('ix_frota_abastecimentos_data'))

    op.drop_table('frota_abastecimentos')
    with op.batch_alter_table('cadastros_areas_valores_patrimoniais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_areas_valores_patrimoniais_area_id'))

    op.drop_table('cadastros_areas_valores_patrimoniais')
    with op.batch_alter_table('frota_checklist_modelos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frota_checklist_modelos_tipo_equipamento'))
        batch_op.drop_index(batch_op.f('ix_frota_checklist_modelos_tenant_id'))

    op.drop_table('frota_checklist_modelos')
    # ### end Alembic commands ###
