"""fix_crm_ofertas_metadata_reserved_name

Revision ID: 9f279111cf60
Revises: a0a58168bc5b
Create Date: 2026-03-27 22:16:31.215367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f279111cf60'
down_revision: Union[str, Sequence[str], None] = 'a0a58168bc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
