"""add_rh_colaboradores_diarias_empreitadas

Revision ID: 9fb4d67bd648
Revises: 5acaf7be91a8
Create Date: 2026-03-23 00:34:43.638444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb4d67bd648'
down_revision: Union[str, Sequence[str], None] = '5acaf7be91a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
