"""restore_missing_tables_after_env_metadata_fix

Revision ID: 9fef33b8dd9f
Revises: f1f50a70316c
Create Date: 2026-04-04 15:41:12.085515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fef33b8dd9f'
down_revision: Union[str, Sequence[str], None] = 'f1f50a70316c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversas_agronomo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('contexto_atual', sa.JSON(), nullable=True),
    sa.Column('historico_mensagens', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversas_agronomo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversas_agronomo_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('culturas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nome_cientifico', sa.String(length=150), nullable=True),
    sa.Column('variedade', sa.String(length=100), nullable=True),
    sa.Column('ciclo_dias', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('culturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_culturas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('amb_alertas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=True),
    sa.Column('fazenda_nome', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.Enum('DESMATAMENTO', 'QUEIMADA', 'INUNDACAO', 'EROSAO', 'OUTRO', name='tipoalerta'), nullable=False),
    sa.Column('severidade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='severidadealerta'), nullable=False),
    sa.Column('status', sa.Enum('NOVO', 'EM_ANALISE', 'RESOLVIDO', 'IGNORADO', name='statusalerta'), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fonte', sa.String(length=100), nullable=True, comment='PRODES | DETER | SICAR | MANUAL'),
    sa.Column('talhao_nome', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('data_deteccao', sa.Date(), nullable=False),
    sa.Column('data_resolucao', sa.Date(), nullable=True),
    sa.Column('resolucao_descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amb_alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amb_alertas_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amb_alertas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('amb_outorgas_hidricas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=True),
    sa.Column('fazenda_nome', sa.String(length=200), nullable=True),
    sa.Column('numero_outorga', sa.String(length=100), nullable=False),
    sa.Column('orgao_emissor', sa.String(length=100), nullable=True),
    sa.Column('tipo_uso', sa.Enum('IRRIGACAO', 'DESSEDENTACAO', 'USO_INDUSTRIAL', 'AQUICULTURA', 'OUTRO', name='tipousooutorga'), nullable=False),
    sa.Column('corpo_hidrico', sa.String(length=200), nullable=True),
    sa.Column('vazao_outorgada_ls', sa.Float(), nullable=True),
    sa.Column('vazao_outorgada_m3h', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ATIVA', 'VENCIDA', 'SUSPENSA', 'CANCELADA', 'EM_RENOVACAO', name='statusoutorga'), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amb_outorgas_hidricas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amb_outorgas_hidricas_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amb_outorgas_hidricas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('amb_registros_car',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=True),
    sa.Column('fazenda_nome', sa.String(length=200), nullable=False),
    sa.Column('codigo_car', sa.String(length=50), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'PENDENTE', 'CANCELADO', 'SUSPENSO', 'EM_ANALISE', name='statuscar'), nullable=False),
    sa.Column('area_total_ha', sa.Float(), nullable=True),
    sa.Column('area_app_ha', sa.Float(), nullable=True),
    sa.Column('area_rl_ha', sa.Float(), nullable=True),
    sa.Column('area_vegetacao_nativa_ha', sa.Float(), nullable=True),
    sa.Column('area_uso_consolidado_ha', sa.Float(), nullable=True),
    sa.Column('data_inscricao', sa.Date(), nullable=True),
    sa.Column('data_atualizacao', sa.Date(), nullable=True),
    sa.Column('pendencias', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amb_registros_car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amb_registros_car_codigo_car'), ['codigo_car'], unique=False)
        batch_op.create_index(batch_op.f('ix_amb_registros_car_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amb_registros_car_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('certificacoes_propriedade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('extensao', sa.String(length=100), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('orgao_certificador', sa.String(length=100), nullable=True),
    sa.Column('numero_registro', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('link_documento', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificacoes_propriedade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificacoes_propriedade_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('registros_clima',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=False),
    sa.Column('precipitacao_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temp_max_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_min_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp_media_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('umidade_rel_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('evapotranspiracao_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('gdu_calculado', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fonte', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_clima', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_clima_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_clima_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('imagens_ndvi',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('data_captura', sa.Date(), nullable=False),
    sa.Column('cobertura_nuvens_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('indice_medio', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('indice_minimo', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('indice_maximo', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('url_imagem_colorida', sa.String(length=500), nullable=True),
    sa.Column('url_raw_data', sa.String(length=500), nullable=True),
    sa.Column('satelite', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['talhao_id'], ['cadastros_areas_rurais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imagens_ndvi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imagens_ndvi_talhao_id'), ['talhao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imagens_ndvi_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lotes_rastreabilidade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=50), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('produto', sa.String(length=100), nullable=False),
    sa.Column('variedade', sa.String(length=100), nullable=True),
    sa.Column('quantidade_total', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('qr_code_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('certificacoes', sa.JSON(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['cadastros_areas_rurais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_lote')
    )
    with op.batch_alter_table('lotes_rastreabilidade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotes_rastreabilidade_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('relatorios_tecnicos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('data_visita', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('estadio_fenologico', sa.String(length=50), nullable=True),
    sa.Column('condicao_climatica', sa.JSON(), nullable=True),
    sa.Column('observacoes_gerais', sa.String(length=2000), nullable=True),
    sa.Column('recomendacoes', sa.String(length=2000), nullable=True),
    sa.Column('constatacoes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['talhoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relatorios_tecnicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relatorios_tecnicos_safra_id'), ['safra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relatorios_tecnicos_talhao_id'), ['talhao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relatorios_tecnicos_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios_tecnicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relatorios_tecnicos_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_relatorios_tecnicos_talhao_id'))
        batch_op.drop_index(batch_op.f('ix_relatorios_tecnicos_safra_id'))

    op.drop_table('relatorios_tecnicos')
    with op.batch_alter_table('lotes_rastreabilidade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotes_rastreabilidade_tenant_id'))

    op.drop_table('lotes_rastreabilidade')
    with op.batch_alter_table('imagens_ndvi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imagens_ndvi_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_imagens_ndvi_talhao_id'))

    op.drop_table('imagens_ndvi')
    with op.batch_alter_table('registros_clima', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_clima_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_registros_clima_fazenda_id'))

    op.drop_table('registros_clima')
    with op.batch_alter_table('certificacoes_propriedade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificacoes_propriedade_tenant_id'))

    op.drop_table('certificacoes_propriedade')
    with op.batch_alter_table('amb_registros_car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amb_registros_car_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_amb_registros_car_fazenda_id'))
        batch_op.drop_index(batch_op.f('ix_amb_registros_car_codigo_car'))

    op.drop_table('amb_registros_car')
    with op.batch_alter_table('amb_outorgas_hidricas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amb_outorgas_hidricas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_amb_outorgas_hidricas_fazenda_id'))

    op.drop_table('amb_outorgas_hidricas')
    with op.batch_alter_table('amb_alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amb_alertas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_amb_alertas_fazenda_id'))

    op.drop_table('amb_alertas')
    with op.batch_alter_table('culturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_culturas_tenant_id'))

    op.drop_table('culturas')
    with op.batch_alter_table('conversas_agronomo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversas_agronomo_tenant_id'))

    op.drop_table('conversas_agronomo')
    # ### end Alembic commands ###
