"""refactor_despesas_receitas_add_pessoa_parcelas_fiscal

Revision ID: a1aba30b643a
Revises: 5d371c3cd756
Create Date: 2026-03-22 22:31:39.928995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1aba30b643a'
down_revision: Union[str, Sequence[str], None] = '5d371c3cd756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fin_despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pessoa_id', sa.Uuid(), nullable=True, comment='Fornecedor/prestador cadastrado. Se NULL, usar campo fornecedor (texto livre)'))
        batch_op.add_column(sa.Column('valor_pago', sa.Numeric(precision=14, scale=2), nullable=True, comment='Valor efetivamente pago (pode ser parcial)'))
        batch_op.add_column(sa.Column('competencia', sa.Date(), nullable=True, comment='Mês/ano de competência fiscal para Livro Caixa (geralmente 1º dia do mês)'))
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=20), nullable=True, comment='PIX, BOLETO, TRANSFERENCIA, DINHEIRO, CARTAO, CHEQUE, DEBITO_AUTOMATICO'))
        batch_op.add_column(sa.Column('grupo_parcela_id', sa.Uuid(), nullable=True, comment='Agrupa todas as parcelas do mesmo lançamento parcelado'))
        batch_op.add_column(sa.Column('numero_parcela', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_parcelas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numero_nf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('serie_nf', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('chave_nfe', sa.String(length=44), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.alter_column('valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_fin_despesas_data_vencimento'), ['data_vencimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_despesas_grupo_parcela_id'), ['grupo_parcela_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_despesas_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_foreign_key(None, 'pessoas', ['pessoa_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fin_receitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pessoa_id', sa.Uuid(), nullable=True, comment='Cliente/comprador cadastrado. Se NULL, usar campo cliente (texto livre)'))
        batch_op.add_column(sa.Column('valor_recebido', sa.Numeric(precision=14, scale=2), nullable=True, comment='Valor efetivamente recebido (pode ser parcial)'))
        batch_op.add_column(sa.Column('competencia', sa.Date(), nullable=True, comment='Mês/ano de competência fiscal para Livro Caixa (geralmente 1º dia do mês)'))
        batch_op.add_column(sa.Column('forma_recebimento', sa.String(length=20), nullable=True, comment='PIX, BOLETO, TRANSFERENCIA, DINHEIRO, CARTAO, CHEQUE'))
        batch_op.add_column(sa.Column('grupo_parcela_id', sa.Uuid(), nullable=True, comment='Agrupa todas as parcelas do mesmo lançamento parcelado'))
        batch_op.add_column(sa.Column('numero_parcela', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_parcelas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numero_nf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('serie_nf', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('chave_nfe', sa.String(length=44), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.alter_column('valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_fin_receitas_data_vencimento'), ['data_vencimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_receitas_grupo_parcela_id'), ['grupo_parcela_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_receitas_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_foreign_key(None, 'pessoas', ['pessoa_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fin_receitas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fin_receitas_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_fin_receitas_grupo_parcela_id'))
        batch_op.drop_index(batch_op.f('ix_fin_receitas_data_vencimento'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('valor_total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('observacoes')
        batch_op.drop_column('chave_nfe')
        batch_op.drop_column('serie_nf')
        batch_op.drop_column('numero_nf')
        batch_op.drop_column('total_parcelas')
        batch_op.drop_column('numero_parcela')
        batch_op.drop_column('grupo_parcela_id')
        batch_op.drop_column('forma_recebimento')
        batch_op.drop_column('competencia')
        batch_op.drop_column('valor_recebido')
        batch_op.drop_column('pessoa_id')

    with op.batch_alter_table('fin_despesas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fin_despesas_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_fin_despesas_grupo_parcela_id'))
        batch_op.drop_index(batch_op.f('ix_fin_despesas_data_vencimento'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('valor_total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('observacoes')
        batch_op.drop_column('chave_nfe')
        batch_op.drop_column('serie_nf')
        batch_op.drop_column('numero_nf')
        batch_op.drop_column('total_parcelas')
        batch_op.drop_column('numero_parcela')
        batch_op.drop_column('grupo_parcela_id')
        batch_op.drop_column('forma_pagamento')
        batch_op.drop_column('competencia')
        batch_op.drop_column('valor_pago')
        batch_op.drop_column('pessoa_id')

    # ### end Alembic commands ###
