"""onda1_recebimento_devolucao_tabelas

Revision ID: a7f302ced8ad
Revises: 5f203e4d3e53
Create Date: 2026-03-23 19:08:47.158515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f302ced8ad'
down_revision: Union[str, Sequence[str], None] = '5f203e4d3e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
