"""monitoramento_catalogo_nde

Revision ID: abbf2ef99219
Revises: 6254ef5f6fa6
Create Date: 2026-03-27 16:27:00.740999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abbf2ef99219'
down_revision: Union[str, Sequence[str], None] = '6254ef5f6fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fenologia_escalas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('cultura', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fenologia_escalas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fenologia_escalas_cultura'), ['cultura'], unique=False)
        batch_op.create_index(batch_op.f('ix_fenologia_escalas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('monitoramento_catalogo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome_popular', sa.String(length=100), nullable=False),
    sa.Column('nome_cientifico', sa.String(length=100), nullable=True),
    sa.Column('cultura', sa.String(length=50), nullable=True),
    sa.Column('nde_padrao', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('unidade_medida', sa.String(length=30), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoramento_catalogo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoramento_catalogo_cultura'), ['cultura'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoramento_catalogo_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoramento_catalogo_tipo'), ['tipo'], unique=False)

    op.create_table('safra_talhao_grupos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safra_talhao_grupos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safra_talhao_grupos_safra_id'), ['safra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_talhao_grupos_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('safra_fenologia_registros',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('escala_id', sa.Uuid(), nullable=False),
    sa.Column('grupo_id', sa.Uuid(), nullable=True),
    sa.Column('data_observacao', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('dados_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['escala_id'], ['fenologia_escalas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grupo_id'], ['safra_talhao_grupos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['cadastros_areas_rurais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safra_fenologia_registros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safra_fenologia_registros_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_fenologia_registros_safra_id'), ['safra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_fenologia_registros_talhao_id'), ['talhao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_fenologia_registros_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('safra_talhao_grupo_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grupo_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['safra_talhao_grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['cadastros_areas_rurais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safra_talhao_grupo_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safra_talhao_grupo_itens_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_talhao_grupo_itens_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('monitoramento_pragas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalogo_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('estagio_fenologico_codigo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estagio_fenologico_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('acao_tomada', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_foreign_key(None, 'monitoramento_catalogo', ['catalogo_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'safra_fenologia_registros', ['estagio_fenologico_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoramento_pragas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('acao_tomada')
        batch_op.drop_column('estagio_fenologico_id')
        batch_op.drop_column('estagio_fenologico_codigo')
        batch_op.drop_column('catalogo_id')

    with op.batch_alter_table('safra_talhao_grupo_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safra_talhao_grupo_itens_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_safra_talhao_grupo_itens_grupo_id'))

    op.drop_table('safra_talhao_grupo_itens')
    with op.batch_alter_table('safra_fenologia_registros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safra_fenologia_registros_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_safra_fenologia_registros_talhao_id'))
        batch_op.drop_index(batch_op.f('ix_safra_fenologia_registros_safra_id'))
        batch_op.drop_index(batch_op.f('ix_safra_fenologia_registros_grupo_id'))

    op.drop_table('safra_fenologia_registros')
    with op.batch_alter_table('safra_talhao_grupos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safra_talhao_grupos_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_safra_talhao_grupos_safra_id'))

    op.drop_table('safra_talhao_grupos')
    with op.batch_alter_table('monitoramento_catalogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoramento_catalogo_tipo'))
        batch_op.drop_index(batch_op.f('ix_monitoramento_catalogo_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_monitoramento_catalogo_cultura'))

    op.drop_table('monitoramento_catalogo')
    with op.batch_alter_table('fenologia_escalas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fenologia_escalas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_fenologia_escalas_cultura'))

    op.drop_table('fenologia_escalas')
    # ### end Alembic commands ###
