"""cafe_beneficiamento

Revision ID: bfe97b02bbe9
Revises: 1f592f899d93
Create Date: 2026-03-27 18:30:37.439343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe97b02bbe9'
down_revision: Union[str, Sequence[str], None] = '1f592f899d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe_lotes_beneficiamento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('talhao_id', sa.Uuid(), nullable=True),
    sa.Column('numero_lote', sa.String(length=30), nullable=False),
    sa.Column('metodo', sa.String(length=20), nullable=False, comment='NATURAL, LAVADO, HONEY, DESCASCADO'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='RECEBIMENTO, SECAGEM, CLASSIFICACAO, ARMAZENADO, VENDIDO'),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('peso_entrada_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('umidade_entrada_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Umidade na entrada: cereja ~55-65%, coco ~30-40%'),
    sa.Column('local_secagem', sa.String(length=30), nullable=True, comment='TERREIRO_CIMENTO, TERREIRO_SUSPENSO, SECADOR_MECANICO, MISTO'),
    sa.Column('data_inicio_secagem', sa.Date(), nullable=True),
    sa.Column('data_fim_secagem', sa.Date(), nullable=True),
    sa.Column('dias_secagem', sa.Integer(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('peso_saida_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('umidade_saida_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Umidade final: padrão MAPA = 12%'),
    sa.Column('fator_reducao', sa.Numeric(precision=6, scale=3), nullable=True, comment='Relação entrada/saída. Ex: 4.8 = 4,8 kg cereja → 1 kg beneficiado'),
    sa.Column('sacas_beneficiadas', sa.Numeric(precision=10, scale=3), nullable=True, comment='Sacas de 60 kg de café beneficiado'),
    sa.Column('perda_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='% de perda no processamento vs. esperado'),
    sa.Column('peneira_principal', sa.String(length=10), nullable=True, comment='Peneira predominante: 17+, 15/16, 13/14, etc.'),
    sa.Column('bebida', sa.String(length=30), nullable=True, comment='Classificação ABIC: ESTRITAMENTE_MOLE, MOLE, APENAS_MOLE, DURA, RIADA, RIO'),
    sa.Column('pontuacao_scaa', sa.Numeric(precision=4, scale=2), nullable=True, comment='Pontuação SCA (0-100). ≥ 80 = specialty coffee'),
    sa.Column('defeitos_intrinsecos', sa.Integer(), nullable=True),
    sa.Column('defeitos_extrinsecos', sa.Integer(), nullable=True),
    sa.Column('armazem_id', sa.Uuid(), nullable=True),
    sa.Column('saca_inicio', sa.Integer(), nullable=True, comment='Nº da primeira saca'),
    sa.Column('saca_fim', sa.Integer(), nullable=True, comment='Nº da última saca'),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['talhao_id'], ['cadastros_areas_rurais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cafe_lotes_beneficiamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cafe_lotes_beneficiamento_safra_id'), ['safra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cafe_lotes_beneficiamento_talhao_id'), ['talhao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cafe_lotes_beneficiamento_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe_lotes_beneficiamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cafe_lotes_beneficiamento_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cafe_lotes_beneficiamento_talhao_id'))
        batch_op.drop_index(batch_op.f('ix_cafe_lotes_beneficiamento_safra_id'))

    op.drop_table('cafe_lotes_beneficiamento')
    # ### end Alembic commands ###
