"""cadastros_pessoas_lgpd

Revision ID: c157f09d6817
Revises: f1569f5e75f7
Create Date: 2026-03-24 00:52:15.035325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c157f09d6817'
down_revision: Union[str, Sequence[str], None] = 'f1569f5e75f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastros_pessoas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=2), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=200), nullable=False),
    sa.Column('base_legal', sa.String(length=30), nullable=False),
    sa.Column('reter_dados_ate', sa.Date(), nullable=True),
    sa.Column('anonimizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_pessoas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_nome_exibicao'), ['nome_exibicao'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cadastros_tipos_relacionamento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('icone', sa.String(length=50), nullable=False),
    sa.Column('sistema', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_tipos_relacionamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_tipos_relacionamento_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_tipos_relacionamento_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cadastros_pessoas_acesso_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('campos_acessados', sa.JSON(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_pessoas_acesso_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_acesso_log_pessoa_id'), ['pessoa_id'], unique=False)

    op.create_table('cadastros_pessoas_consentimentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('finalidade', sa.String(length=50), nullable=False),
    sa.Column('concedido', sa.Boolean(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('versao_politica', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_pessoas_consentimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_consentimentos_pessoa_id'), ['pessoa_id'], unique=False)

    op.create_table('cadastros_pessoas_enderecos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('pais', sa.String(length=3), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_pessoas_enderecos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_enderecos_pessoa_id'), ['pessoa_id'], unique=False)

    op.create_table('cadastros_pessoas_pii',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('rg', sa.String(length=30), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('ie', sa.String(length=30), nullable=True),
    sa.Column('data_fundacao', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_pessoas_pii', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_pii_pessoa_id'), ['pessoa_id'], unique=True)

    op.create_table('cadastros_pessoa_relacionamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo_desde', sa.Date(), nullable=True),
    sa.Column('ativo_ate', sa.Date(), nullable=True),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_id'], ['cadastros_tipos_relacionamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_pessoa_relacionamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoa_relacionamentos_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_pessoa_relacionamentos_pessoa_id'), ['pessoa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_pessoa_relacionamentos_tipo_id'), ['tipo_id'], unique=False)

    with op.batch_alter_table('estoque_lotes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('estoque_lotes_produto_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cadastros_produtos', ['produto_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('estoque_movimentacoes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('estoque_movimentacoes_produto_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cadastros_produtos', ['produto_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('estoque_reservas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('estoque_reservas_produto_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cadastros_produtos', ['produto_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('estoque_saldos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('estoque_saldos_produto_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cadastros_produtos', ['produto_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_saldos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('estoque_saldos_produto_id_fkey'), 'cadastros_produtos', ['produto_id'], ['id'])

    with op.batch_alter_table('estoque_reservas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('estoque_reservas_produto_id_fkey'), 'cadastros_produtos', ['produto_id'], ['id'])

    with op.batch_alter_table('estoque_movimentacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('estoque_movimentacoes_produto_id_fkey'), 'cadastros_produtos', ['produto_id'], ['id'])

    with op.batch_alter_table('estoque_lotes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('estoque_lotes_produto_id_fkey'), 'cadastros_produtos', ['produto_id'], ['id'])

    with op.batch_alter_table('cadastros_pessoa_relacionamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoa_relacionamentos_tipo_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoa_relacionamentos_pessoa_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoa_relacionamentos_fazenda_id'))

    op.drop_table('cadastros_pessoa_relacionamentos')
    with op.batch_alter_table('cadastros_pessoas_pii', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_pii_pessoa_id'))

    op.drop_table('cadastros_pessoas_pii')
    with op.batch_alter_table('cadastros_pessoas_enderecos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_enderecos_pessoa_id'))

    op.drop_table('cadastros_pessoas_enderecos')
    with op.batch_alter_table('cadastros_pessoas_consentimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_consentimentos_pessoa_id'))

    op.drop_table('cadastros_pessoas_consentimentos')
    with op.batch_alter_table('cadastros_pessoas_acesso_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_acesso_log_pessoa_id'))

    op.drop_table('cadastros_pessoas_acesso_log')
    with op.batch_alter_table('cadastros_tipos_relacionamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_tipos_relacionamento_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_tipos_relacionamento_codigo'))

    op.drop_table('cadastros_tipos_relacionamento')
    with op.batch_alter_table('cadastros_pessoas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_nome_exibicao'))

    op.drop_table('cadastros_pessoas')
    # ### end Alembic commands ###
