"""add_estoque_tipo_uso_ativo_custo_fields

Revision ID: c28e38e960aa
Revises: c73c38421889
Create Date: 2026-03-22 23:31:25.765492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28e38e960aa'
down_revision: Union[str, Sequence[str], None] = 'c73c38421889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_movimentacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custo_unitario', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('custo_total', sa.Float(), nullable=True))

    with op.batch_alter_table('estoque_produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_uso', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_estoque_produtos_nome'), ['nome'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque_produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoque_produtos_nome'))
        batch_op.drop_column('ativo')
        batch_op.drop_column('tipo_uso')

    with op.batch_alter_table('estoque_movimentacoes', schema=None) as batch_op:
        batch_op.drop_column('custo_total')
        batch_op.drop_column('custo_unitario')

    # ### end Alembic commands ###
