"""add_agricola_orcamento_itens

Revision ID: c73c38421889
Revises: f37b19542d58
Create Date: 2026-03-22 22:59:26.553266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73c38421889'
down_revision: Union[str, Sequence[str], None] = 'f37b19542d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agricola_orcamento_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('safra_id', sa.Uuid(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False, comment='kg, L, sc, d/H, ha, etc.'),
    sa.Column('custo_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('custo_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agricola_orcamento_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agricola_orcamento_itens_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_agricola_orcamento_itens_safra_id'), ['safra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agricola_orcamento_itens_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agricola_orcamento_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agricola_orcamento_itens_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agricola_orcamento_itens_safra_id'))
        batch_op.drop_index(batch_op.f('ix_agricola_orcamento_itens_categoria'))

    op.drop_table('agricola_orcamento_itens')
    # ### end Alembic commands ###
