"""add_logo_url_to_unidades_produtivas

Revision ID: c853a6f175f1
Revises: 0ebcf9f198d0
Create Date: 2026-04-10 11:19:47.400163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c853a6f175f1'
down_revision: Union[str, Sequence[str], None] = '0ebcf9f198d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_impersonations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=True, comment='Fazenda específica sendo acessada (NULL = contexto geral do tenant)'))
        batch_op.drop_constraint(batch_op.f('admin_impersonations_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('amb_alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_amb_alertas_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_amb_alertas_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('amb_alertas_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('amb_outorgas_hidricas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_amb_outorgas_hidricas_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_amb_outorgas_hidricas_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('amb_outorgas_hidricas_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('amb_registros_car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_amb_registros_car_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_amb_registros_car_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('amb_registros_car_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('assinaturas_tenant', schema=None) as batch_op:
        batch_op.alter_column('tipo_assinatura',
               existing_type=sa.VARCHAR(length=20),
               comment='TENANT (assinatura do tenant) | ADICIONAL (add-on de módulos extras)',
               existing_comment='GRUPO (assinatura base do grupo) | ADICIONAL (add-on de módulos extras)',
               existing_nullable=False,
               existing_server_default=sa.text("'PRINCIPAL'::character varying"))
        batch_op.create_unique_constraint('uq_assinatura_tenant_tipo', ['tenant_id', 'tipo_assinatura'])

    with op.batch_alter_table('cadastros_areas_rurais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_areas_rurais_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_cadastros_areas_rurais_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('cadastros_equipamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_equipamentos_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_cadastros_equipamentos_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('cadastros_exploracoes_rurais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_cadastros_exploracoes_rurais_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_cadastros_exploracoes_rurais_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('cadastros_exploracoes_rurais_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('cadastros_pessoa_relacionamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoa_relacionamentos_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_cadastros_pessoa_relacionamentos_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('cadastros_pessoa_relacionamentos_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'])
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('certificacoes_propriedade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=False))
        batch_op.drop_constraint(batch_op.f('certificacoes_propriedade_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('configuracao_fazenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracao_fazenda_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_configuracao_fazenda_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=True)

    with op.batch_alter_table('convites_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidades_produtivas_ids', sa.JSON(), nullable=False))
        batch_op.drop_column('fazendas_ids')

    with op.batch_alter_table('estoque_depositos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_estoque_depositos_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_estoque_depositos_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('estoque_depositos_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'])
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('estoque_requisicoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_estoque_requisicoes_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_estoque_requisicoes_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('estoque_requisicoes_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'])
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('fin_contas_bancarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fin_contas_bancarias_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('fin_despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_despesas_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_fin_despesas_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('fin_receitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_receitas_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_fin_receitas_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('frota_apontamentos_uso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=True))
        batch_op.drop_constraint(batch_op.f('frota_apontamentos_uso_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('imoveis_arrendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_imoveis_arrendamentos_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_imoveis_arrendamentos_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('imoveis_arrendamentos_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('imoveis_rurais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_imoveis_rurais_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_imoveis_rurais_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('imoveis_rurais_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('pec_animais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_animais_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_pec_animais_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('pec_lotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_lotes_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_pec_lotes_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('pec_piquetes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_piquetes_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_pec_piquetes_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('pec_producao_leite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_producao_leite_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_pec_producao_leite_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('registros_clima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_registros_clima_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_registros_clima_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('registros_clima_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('rh_colaboradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rh_colaboradores_fazenda_id'))
        batch_op.create_index(batch_op.f('ix_rh_colaboradores_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('rh_lancamentos_diarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_produtiva_id', sa.Uuid(), nullable=True))
        batch_op.drop_constraint(batch_op.f('rh_lancamentos_diarias_fazenda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'unidades_produtivas', ['unidade_produtiva_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('fazenda_id')

    with op.batch_alter_table('sessoes_ativas', schema=None) as batch_op:
        batch_op.create_index('idx_sessoes_limite_tenant', ['tenant_id', 'status', 'expira_em'], unique=False)

    with op.batch_alter_table('unidade_produtiva_usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fazenda_usuarios_fazenda_id'))
        batch_op.drop_index(batch_op.f('ix_fazenda_usuarios_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_fazenda_usuarios_vigencia_fim'))
        batch_op.create_index(batch_op.f('ix_unidade_produtiva_usuarios_unidade_produtiva_id'), ['unidade_produtiva_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unidade_produtiva_usuarios_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unidade_produtiva_usuarios_vigencia_fim'), ['vigencia_fim'], unique=False)

    with op.batch_alter_table('unidades_produtivas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True, comment='URL do logotipo da propriedade'))
        batch_op.drop_index(batch_op.f('ix_fazendas_tenant_id'))
        batch_op.create_index(batch_op.f('ix_unidades_produtivas_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades_produtivas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidades_produtivas_tenant_id'))
        batch_op.create_index(batch_op.f('ix_fazendas_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_column('logo_url')

    with op.batch_alter_table('unidade_produtiva_usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidade_produtiva_usuarios_vigencia_fim'))
        batch_op.drop_index(batch_op.f('ix_unidade_produtiva_usuarios_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_unidade_produtiva_usuarios_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_fazenda_usuarios_vigencia_fim'), ['vigencia_fim'], unique=False)
        batch_op.create_index(batch_op.f('ix_fazenda_usuarios_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fazenda_usuarios_fazenda_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('sessoes_ativas', schema=None) as batch_op:
        batch_op.drop_index('idx_sessoes_limite_tenant')

    with op.batch_alter_table('rh_lancamentos_diarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rh_lancamentos_diarias_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('rh_colaboradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rh_colaboradores_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_rh_colaboradores_fazenda_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('registros_clima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('registros_clima_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_registros_clima_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_registros_clima_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('pec_producao_leite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_producao_leite_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_pec_producao_leite_fazenda_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('pec_piquetes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_piquetes_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_pec_piquetes_fazenda_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('pec_lotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_lotes_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_pec_lotes_fazenda_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('pec_animais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pec_animais_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_pec_animais_fazenda_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('imoveis_rurais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('imoveis_rurais_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_imoveis_rurais_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_imoveis_rurais_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('imoveis_arrendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('imoveis_arrendamentos_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_imoveis_arrendamentos_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_imoveis_arrendamentos_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('frota_apontamentos_uso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('frota_apontamentos_uso_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('fin_receitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_receitas_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_fin_receitas_fazenda_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('fin_despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_despesas_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_fin_despesas_fazenda_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('fin_contas_bancarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fin_contas_bancarias_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('estoque_requisicoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('estoque_requisicoes_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_estoque_requisicoes_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_estoque_requisicoes_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('estoque_depositos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('estoque_depositos_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_estoque_depositos_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_estoque_depositos_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('convites_acesso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazendas_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_column('unidades_produtivas_ids')

    with op.batch_alter_table('configuracao_fazenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracao_fazenda_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_configuracao_fazenda_fazenda_id'), ['unidade_produtiva_id'], unique=True)

    with op.batch_alter_table('certificacoes_propriedade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('certificacoes_propriedade_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('cadastros_pessoa_relacionamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cadastros_pessoa_relacionamentos_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoa_relacionamentos_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_cadastros_pessoa_relacionamentos_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('cadastros_exploracoes_rurais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cadastros_exploracoes_rurais_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_cadastros_exploracoes_rurais_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_cadastros_exploracoes_rurais_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('cadastros_equipamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_equipamentos_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_cadastros_equipamentos_fazenda_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('cadastros_areas_rurais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_areas_rurais_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_cadastros_areas_rurais_fazenda_id'), ['unidade_produtiva_id'], unique=False)

    with op.batch_alter_table('assinaturas_tenant', schema=None) as batch_op:
        batch_op.drop_constraint('uq_assinatura_tenant_tipo', type_='unique')
        batch_op.alter_column('tipo_assinatura',
               existing_type=sa.VARCHAR(length=20),
               comment='GRUPO (assinatura base do grupo) | ADICIONAL (add-on de módulos extras)',
               existing_comment='TENANT (assinatura do tenant) | ADICIONAL (add-on de módulos extras)',
               existing_nullable=False,
               existing_server_default=sa.text("'PRINCIPAL'::character varying"))

    with op.batch_alter_table('amb_registros_car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('amb_registros_car_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_amb_registros_car_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_amb_registros_car_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('amb_outorgas_hidricas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('amb_outorgas_hidricas_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_amb_outorgas_hidricas_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_amb_outorgas_hidricas_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('amb_alertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('amb_alertas_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_amb_alertas_unidade_produtiva_id'))
        batch_op.create_index(batch_op.f('ix_amb_alertas_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.drop_column('unidade_produtiva_id')

    with op.batch_alter_table('admin_impersonations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=True, comment='Fazenda específica sendo acessada (NULL = contexto geral do tenant)'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('admin_impersonations_fazenda_id_fkey'), 'unidades_produtivas', ['fazenda_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('unidade_produtiva_id')

    # ### end Alembic commands ###
