"""add_financial_fields_to_manejo_lote

Revision ID: cd26bb50a28e
Revises: 3369ff8cc948
Create Date: 2026-03-23 08:52:21.272996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd26bb50a28e'
down_revision: Union[str, Sequence[str], None] = '3369ff8cc948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pec_manejos_lote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custo_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_venda', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pec_manejos_lote', schema=None) as batch_op:
        batch_op.drop_column('valor_venda')
        batch_op.drop_column('custo_total')

    # ### end Alembic commands ###
