"""add_compras_recebimento_fields

Revision ID: ea1498232c05
Revises: 02e5c1fef995
Create Date: 2026-03-22 23:39:08.982364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1498232c05'
down_revision: Union[str, Sequence[str], None] = '02e5c1fef995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras_itens_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_recebida', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('preco_real_unitario', sa.Float(), nullable=True))

    with op.batch_alter_table('compras_pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposito_destino_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('data_recebimento', sa.Date(), nullable=True))
        batch_op.create_foreign_key(None, 'estoque_depositos', ['deposito_destino_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras_pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_recebimento')
        batch_op.drop_column('deposito_destino_id')

    with op.batch_alter_table('compras_itens_pedido', schema=None) as batch_op:
        batch_op.drop_column('preco_real_unitario')
        batch_op.drop_column('quantidade_recebida')

    # ### end Alembic commands ###
