"""romaneios_produtividade

Revision ID: eaeeac2f9a86
Revises: 6f813e2a6f13
Create Date: 2026-03-27 17:15:45.236255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaeeac2f9a86'
down_revision: Union[str, Sequence[str], None] = '6f813e2a6f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('romaneios_colheita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produtividade_sc_ha', sa.Numeric(precision=10, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('romaneios_colheita', schema=None) as batch_op:
        batch_op.drop_column('produtividade_sc_ha')

    # ### end Alembic commands ###
