"""onda2_produtos_commodities

Revision ID: ed0688180f35
Revises: fa37f6f94792
Create Date: 2026-03-24 23:09:49.589174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed0688180f35'
down_revision: Union[str, Sequence[str], None] = 'fa37f6f94792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastros_commodities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('unidade_padrao', sa.String(length=20), nullable=False),
    sa.Column('fator_conversao_kg', sa.Float(), nullable=True, comment='Peso em KG de 1 unidade padrão. Ex: SACA_60KG=60, ARROBA=15'),
    sa.Column('umidade_padrao_pct', sa.Float(), nullable=True, comment='Ex: 14.0 para soja'),
    sa.Column('impureza_padrao_pct', sa.Float(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_commodities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_commodities_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_commodities_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_commodities_tipo'), ['tipo'], unique=False)

    op.create_table('cadastros_culturas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nome_cientifico', sa.String(length=150), nullable=True),
    sa.Column('grupo', sa.String(length=50), nullable=True, comment='GRAOS | FIBRAS | FRUTAS | HORTALICAS | PASTAGEM | OUTRO'),
    sa.Column('ciclo_dias_min', sa.Integer(), nullable=True),
    sa.Column('ciclo_dias_max', sa.Integer(), nullable=True),
    sa.Column('espacamento_cm', sa.Float(), nullable=True),
    sa.Column('populacao_plantas_ha', sa.Integer(), nullable=True),
    sa.Column('produtividade_media_sc_ha', sa.Float(), nullable=True),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_culturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_culturas_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_culturas_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cadastros_commodities_classificacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('commodity_id', sa.Uuid(), nullable=False),
    sa.Column('classe', sa.String(length=50), nullable=False, comment='TIPO_1 | TIPO_2 | FORA_TIPO | ESPECIAL | PREMIUM'),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('umidade_max_pct', sa.Float(), nullable=True),
    sa.Column('impureza_max_pct', sa.Float(), nullable=True),
    sa.Column('avariados_max_pct', sa.Float(), nullable=True),
    sa.Column('ardidos_max_pct', sa.Float(), nullable=True),
    sa.Column('esverdeados_max_pct', sa.Float(), nullable=True),
    sa.Column('quebrados_max_pct', sa.Float(), nullable=True),
    sa.Column('desconto_umidade_por_ponto', sa.Float(), nullable=True),
    sa.Column('desconto_impureza_por_ponto', sa.Float(), nullable=True),
    sa.Column('parametros_extras', sa.JSON(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['cadastros_commodities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_commodities_classificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_commodities_classificacoes_commodity_id'), ['commodity_id'], unique=False)

    op.create_table('cadastros_produtos_epi',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('ca_numero', sa.String(length=20), nullable=True, comment='Certificado de Aprovação MTE'),
    sa.Column('ca_validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo_protecao', sa.String(length=100), nullable=True, comment='CABECA | OLHOS | RESPIRATORIO | MAOS | PES | CORPO | AUDITIVO | QUEDAS'),
    sa.Column('vida_util_meses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['cadastros_produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_produtos_epi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_produtos_epi_produto_id'), ['produto_id'], unique=True)

    # Migrar dados de culturas → cadastros_culturas antes de recriar a FK
    op.execute("""
        INSERT INTO cadastros_culturas (id, tenant_id, nome, nome_cientifico, ativa, created_at, updated_at)
        SELECT id, tenant_id, nome, nome_cientifico, ativa, created_at, updated_at
        FROM culturas
        ON CONFLICT (id) DO NOTHING
    """)

    # Remover FK de safras → culturas e recriar apontando para cadastros_culturas
    with op.batch_alter_table('safras', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('safras_cultivar_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cadastros_culturas', ['cultivar_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('culturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_culturas_tenant_id'))

    op.drop_table('culturas')
    with op.batch_alter_table('cadastros_produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_barras', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fabricante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dados_extras', sa.JSON(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('unidade_medida',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('cadastros_produtos_agricola', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classe_toxicologica', sa.String(length=5), nullable=True, comment='I | II | III | IV'))
        batch_op.add_column(sa.Column('intervalo_reentrada_horas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('epi_obrigatorio', sa.JSON(), nullable=True, comment='Lista de EPIs obrigatórios'))
        batch_op.add_column(sa.Column('cultura_alvo', sa.String(length=50), nullable=True, comment='SOJA | MILHO | TRIGO | ALGODAO...'))
        batch_op.add_column(sa.Column('tsi', sa.Boolean(), nullable=False, comment='Tratamento de sementes industrial'))
        batch_op.add_column(sa.Column('pureza_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('germinacao_pct', sa.Float(), nullable=True))
        batch_op.alter_column('classe_agronomica',
               existing_type=sa.VARCHAR(length=50),
               comment='HERBICIDA | FUNGICIDA | INSETICIDA | ACARICIDA | NEMATICIDA',
               existing_nullable=True)
        batch_op.alter_column('principio_ativo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('formulacao',
               existing_type=sa.VARCHAR(length=50),
               comment='CE | SC | WG | EC | SL',
               existing_nullable=True)
        batch_op.drop_column('cultura')

    with op.batch_alter_table('cadastros_produtos_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requer_receituario', sa.Boolean(), nullable=False, comment='Exige receituário para saída (defensivos)'))
        batch_op.alter_column('localizacao_default',
               existing_type=sa.VARCHAR(length=100),
               comment='Prateleira / setor no almoxarifado',
               existing_nullable=True)
        batch_op.alter_column('ncm',
               existing_type=sa.VARCHAR(length=10),
               comment='Nomenclatura Comum do Mercosul',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('safras_cultivar_id_fkey'), 'culturas', ['cultivar_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cadastros_produtos_estoque', schema=None) as batch_op:
        batch_op.alter_column('ncm',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Nomenclatura Comum do Mercosul',
               existing_nullable=True)
        batch_op.alter_column('localizacao_default',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Prateleira / setor no almoxarifado',
               existing_nullable=True)
        batch_op.drop_column('requer_receituario')

    with op.batch_alter_table('cadastros_produtos_agricola', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultura', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('formulacao',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='CE | SC | WG | EC | SL',
               existing_nullable=True)
        batch_op.alter_column('principio_ativo',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('classe_agronomica',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='HERBICIDA | FUNGICIDA | INSETICIDA | ACARICIDA | NEMATICIDA',
               existing_nullable=True)
        batch_op.drop_column('germinacao_pct')
        batch_op.drop_column('pureza_pct')
        batch_op.drop_column('tsi')
        batch_op.drop_column('cultura_alvo')
        batch_op.drop_column('epi_obrigatorio')
        batch_op.drop_column('intervalo_reentrada_horas')
        batch_op.drop_column('classe_toxicologica')

    with op.batch_alter_table('cadastros_produtos', schema=None) as batch_op:
        batch_op.alter_column('unidade_medida',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('dados_extras')
        batch_op.drop_column('fabricante')
        batch_op.drop_column('marca')
        batch_op.drop_column('codigo_barras')

    op.create_table('culturas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nome_cientifico', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('variedade', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ciclo_dias', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ativa', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('culturas_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('culturas_pkey'))
    )
    with op.batch_alter_table('culturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_culturas_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('cadastros_produtos_epi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_produtos_epi_produto_id'))

    op.drop_table('cadastros_produtos_epi')
    with op.batch_alter_table('cadastros_commodities_classificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_commodities_classificacoes_commodity_id'))

    op.drop_table('cadastros_commodities_classificacoes')
    with op.batch_alter_table('cadastros_culturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_culturas_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_culturas_nome'))

    op.drop_table('cadastros_culturas')
    with op.batch_alter_table('cadastros_commodities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_commodities_tipo'))
        batch_op.drop_index(batch_op.f('ix_cadastros_commodities_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_commodities_nome'))

    op.drop_table('cadastros_commodities')
    # ### end Alembic commands ###
