"""feat: add soil type and irrigation models and fields

Revision ID: ef4c538525d1
Revises: 5dbcd798449d
Create Date: 2026-04-21 15:29:59.408959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef4c538525d1'
down_revision: Union[str, Sequence[str], None] = '5dbcd798449d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastros_tipos_irrigacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('metodo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('cadastros_tipos_solo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('retencao_agua', sa.String(length=10), nullable=False),
    sa.Column('lixiviacao', sa.String(length=10), nullable=False),
    sa.Column('ctc_resumo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('agricola_regras_agronomicas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('condicao_json', sa.JSON(), nullable=False),
    sa.Column('acao_json', sa.JSON(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agricola_regras_agronomicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agricola_regras_agronomicas_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('agricola_operacao_tipo_fase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agricola_operacao_tipo_fase_tipo_operacao'))

    op.drop_table('agricola_operacao_tipo_fase')
    with op.batch_alter_table('agricola_orcamento_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultivo_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agricola_orcamento_itens_cultivo_id'), ['cultivo_id'], unique=False)
        batch_op.create_foreign_key(None, 'cultivos', ['cultivo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('agricola_produtos_colhidos', schema=None) as batch_op:
        batch_op.alter_column('romaneio_id',
               existing_type=sa.UUID(),
               comment='Romaneio de colheita que originou este lote (pode ser null se entrada manual)',
               existing_nullable=True)
        batch_op.alter_column('classificacao_id',
               existing_type=sa.UUID(),
               comment='Classificação de mercado atribuída (TIPO_1, PREMIUM, etc.)',
               existing_nullable=True)
        batch_op.alter_column('quantidade',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               comment='Quantidade na unidade da commodity',
               existing_nullable=False)
        batch_op.alter_column('unidade',
               existing_type=sa.VARCHAR(length=20),
               comment='Unidade de medida (herdada da commodity)',
               existing_nullable=False)
        batch_op.alter_column('peso_liquido_kg',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               comment='Peso líquido real em kg',
               existing_nullable=False)
        batch_op.alter_column('destino',
               existing_type=sa.VARCHAR(length=30),
               comment='ARMAZEM | TERCEIRO | VENDIDO | TRANSITO',
               existing_nullable=True)
        batch_op.alter_column('armazem_id',
               existing_type=sa.UUID(),
               comment='Depósito/armazém onde está fisicamente',
               existing_nullable=True)
        batch_op.alter_column('nf_origem',
               existing_type=sa.VARCHAR(length=50),
               comment='NF de origem se veio de terceiro',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='ARMAZENADO | RESERVADO | EM_TRANSITO | VENDIDO | PERDA',
               existing_nullable=False,
               existing_server_default=sa.text("'ARMAZENADO'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('ix_agricola_produtos_colhidos_status'))
        batch_op.drop_constraint(batch_op.f('fk_agricola_produtos_colhidos_cultivo_id'), type_='foreignkey')
        batch_op.drop_column('cultivo_id')

    with op.batch_alter_table('analises_solo', schema=None) as batch_op:
        batch_op.alter_column('saturacao_al_m_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='m% = Al / CTC × 100',
               existing_nullable=True)
        batch_op.alter_column('zinco_zn',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               comment=None,
               existing_comment='mg/dm³',
               existing_nullable=True)
        batch_op.alter_column('boro_b',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               comment=None,
               existing_comment='mg/dm³',
               existing_nullable=True)
        batch_op.alter_column('ferro_fe',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               comment=None,
               existing_comment='mg/dm³',
               existing_nullable=True)
        batch_op.alter_column('manganes_mn',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               comment=None,
               existing_comment='mg/dm³',
               existing_nullable=True)
        batch_op.alter_column('tipo_irrigacao',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='SEQUEIRO | GOTEJAMENTO | PIVO_CENTRAL | ASPERSAO | SULCO',
               existing_nullable=True)
        batch_op.alter_column('sistema_manejo',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='PLANTIO_DIRETO | CONVENCIONAL | MINIMO',
               existing_nullable=True)
        batch_op.alter_column('cultura_nome',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nome da cultura vinculada à análise',
               existing_nullable=True)
        batch_op.alter_column('cultura_anterior',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Cultura plantada anteriormente no talhão',
               existing_nullable=True)
        batch_op.alter_column('validade_meses',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Meses de validade da análise',
               existing_nullable=True,
               existing_server_default=sa.text('12'))

    with op.batch_alter_table('cadastros_areas_rurais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_solo_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('irrigado', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('tipo_irrigacao_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'cadastros_tipos_irrigacao', ['tipo_irrigacao_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'cadastros_tipos_solo', ['tipo_solo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cadastros_commodities', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL = padrão do sistema',
               existing_nullable=True)
        batch_op.alter_column('sistema',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True = não editável pelo tenant',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('peso_unidade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Peso em kg da unidade padrão. Obrigatório para SACA_60KG, TONELADA, KG, ARROBA. Null para CABECA, LITRO, etc.',
               existing_nullable=True)
        batch_op.alter_column('umidade_padrao_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Umidade padrão MAPA para descontos. Ex: 14.0 para soja, 12.0 para café',
               existing_nullable=True)
        batch_op.alter_column('impureza_padrao_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Impureza padrão aceita sem desconto. Ex: 1.0',
               existing_nullable=True)
        batch_op.alter_column('possui_cotacao',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('cadastros_commodities_classificacoes', schema=None) as batch_op:
        batch_op.alter_column('classe',
               existing_type=sa.VARCHAR(length=50),
               comment='TIPO_1 | TIPO_2 | FORA_TIPO | ESPECIAL | PREMIUM',
               existing_nullable=False)
        batch_op.alter_column('desconto_umidade_por_ponto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Desconto % por ponto de umidade acima do máximo',
               existing_nullable=True)
        batch_op.alter_column('desconto_impureza_por_ponto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Desconto % por ponto de impureza acima do máximo',
               existing_nullable=True)
        batch_op.alter_column('parametros_extras',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('cadastros_commodities_cotacoes', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='Preço na unidade padrão da commodity',
               existing_nullable=False)
        batch_op.alter_column('fonte',
               existing_type=sa.VARCHAR(length=50),
               comment='Fonte da cotação: CEPEA, B3, CONAB, MANUAL',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('cadastros_conversao_unidades', schema=None) as batch_op:
        batch_op.alter_column('fator',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='destino = origem × fator',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('cadastros_culturas', schema=None) as batch_op:
        batch_op.alter_column('v_meta_pct_padrao',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               comment=None,
               existing_comment='V% meta padrão para calagem desta cultura',
               existing_nullable=True)

    # batch_op.alter_column('principio_ativo',
    #        existing_type=sa.VARCHAR(length=300),
    #        type_=sa.String(length=30),
    #        existing_nullable=True)

    with op.batch_alter_table('cafe_lote_beneficiamento_romaneios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('cafe_lotes_beneficiamento', schema=None) as batch_op:
        batch_op.alter_column('cultivo_id',
               existing_type=sa.UUID(),
               comment='Cultivo específico processado neste lote (rastreamento de produção por cultura)',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_cafe_lotes_beneficiamento_cultivo_id'), ['cultivo_id'], unique=False)

    with op.batch_alter_table('cultivo_areas', schema=None) as batch_op:
        batch_op.alter_column('analise_solo_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK para analise selecionada para este talhão/cultivo',
               existing_nullable=True)
        batch_op.alter_column('regiao_analise',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Região para lookup de parâmetros: CERRADO | SUL | NORDESTE | SUDESTE | NORTE',
               existing_nullable=True)
        batch_op.alter_column('analise_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='NAO_SELECIONADA | SELECIONADA | REJEITADA',
               existing_nullable=False,
               existing_server_default=sa.text("'NAO_SELECIONADA'::character varying"))
        batch_op.drop_index(batch_op.f('ix_cultivo_areas_analise_solo_id'))
        batch_op.drop_index(batch_op.f('ix_cultivo_areas_analise_status'))
        batch_op.create_index(batch_op.f('ix_cultivo_areas_area_id'), ['area_id'], unique=False)

    with op.batch_alter_table('fin_despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultivo_id', sa.Uuid(), nullable=True, comment='Cultivo específico ao qual a despesa está associada (rastreamento de custo agrícola)'))
        batch_op.create_index(batch_op.f('ix_fin_despesas_cultivo_id'), ['cultivo_id'], unique=False)
        batch_op.create_foreign_key(None, 'cultivos', ['cultivo_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('financeiro_comercializacoes', schema=None) as batch_op:
        batch_op.alter_column('numero_contrato',
               existing_type=sa.VARCHAR(length=30),
               comment='Número do contrato / nota',
               existing_nullable=True)
        batch_op.alter_column('comprador_id',
               existing_type=sa.UUID(),
               comment='Pessoa/empresa compradora',
               existing_nullable=False)
        batch_op.alter_column('quantidade',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               comment='Quantidade na unidade da commodity',
               existing_nullable=False)
        batch_op.alter_column('unidade',
               existing_type=sa.VARCHAR(length=20),
               comment='Unidade de medida (herdada da commodity)',
               existing_nullable=False)
        batch_op.alter_column('preco_unitario',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment='Preço por unidade',
               existing_nullable=False)
        batch_op.alter_column('valor_total',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='quantidade × preco_unitario',
               existing_nullable=False)
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.VARCHAR(length=30),
               comment='A_VISTA | PRAZO | BOLETO | PIX | TRANSFERENCIA',
               existing_nullable=True)
        batch_op.alter_column('local_entrega',
               existing_type=sa.VARCHAR(length=200),
               comment='Endereço/local de entrega',
               existing_nullable=True)
        batch_op.alter_column('frete_por_conta',
               existing_type=sa.VARCHAR(length=20),
               comment='COMPRADOR | VENDEDOR | CIF | FOB',
               existing_nullable=True)
        batch_op.alter_column('produto_colhido_id',
               existing_type=sa.UUID(),
               comment='Lote de produto colhido vinculado (para rastreabilidade e baixa)',
               existing_nullable=True)
        batch_op.alter_column('nf_numero',
               existing_type=sa.VARCHAR(length=50),
               comment='Número da NF-e',
               existing_nullable=True)
        batch_op.alter_column('nf_chave',
               existing_type=sa.VARCHAR(length=44),
               comment='Chave de acesso NF-e',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='RASCUNHO | CONFIRMADO | EM_TRANSITO | ENTREGUE | FINALIZADO | CANCELADO',
               existing_nullable=False,
               existing_server_default=sa.text("'RASCUNHO'::character varying"))
        batch_op.alter_column('receita_id',
               existing_type=sa.UUID(),
               comment='ID da Receita gerada no financeiro',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('ix_financeiro_comercializacoes_status'))

    with op.batch_alter_table('operacoes_agricolas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operacoes_agricolas_cultivo_id'), ['cultivo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operacoes_agricolas_tarefa_id'), ['tarefa_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_operacoes_agricolas_cultivo_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cultivos', ['cultivo_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('romaneios_colheita', schema=None) as batch_op:
        batch_op.alter_column('commodity_id',
               existing_type=sa.UUID(),
               comment='Commodity colhida (derivada de safra.commodity_id, mas explícito para queries)',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_romaneios_colheita_cultivo_id'), ['cultivo_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_romaneios_colheita_cultivo_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cultivos', ['cultivo_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('safra_tarefas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safra_tarefas_cultivo_area_id'), ['cultivo_area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_tarefas_origem'), ['origem'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_tarefas_talhao_id'), ['talhao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safra_tarefas_tipo'), ['tipo'], unique=False)

    with op.batch_alter_table('safras', schema=None) as batch_op:
        batch_op.alter_column('cultura',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('safras_commodity_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('safras_cultivar_id_fkey'), type_='foreignkey')
        batch_op.drop_column('cultivar_id')
        batch_op.drop_column('populacao_prevista')
        batch_op.drop_column('cultivar_nome')
        batch_op.drop_column('sistema_plantio')
        batch_op.drop_column('area_plantada_ha')
        batch_op.drop_column('produtividade_meta_sc_ha')
        batch_op.drop_column('custo_realizado_ha')
        batch_op.drop_column('custo_previsto_ha')
        batch_op.drop_column('commodity_id')
        batch_op.drop_column('produtividade_real_sc_ha')
        batch_op.drop_column('populacao_real')
        batch_op.drop_column('data_plantio_prevista')
        batch_op.drop_column('preco_venda_previsto')
        batch_op.drop_column('data_colheita_prevista')
        batch_op.drop_column('espacamento_cm')
        batch_op.drop_column('data_plantio_real')
        batch_op.drop_column('data_colheita_real')

    with op.batch_alter_table('solo_parametros_cultura', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('ix_solo_params_cultura_lookup'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solo_parametros_cultura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solo_params_cultura_lookup'), ['cultura_id', 'tenant_id', 'parametro', 'regiao'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('safras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_colheita_real', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_plantio_real', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('espacamento_cm', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_colheita_prevista', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preco_venda_previsto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_plantio_prevista', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('populacao_real', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('produtividade_real_sc_ha', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commodity_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custo_previsto_ha', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custo_realizado_ha', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('produtividade_meta_sc_ha', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('area_plantada_ha', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sistema_plantio', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cultivar_nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('populacao_prevista', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cultivar_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('safras_cultivar_id_fkey'), 'cadastros_culturas', ['cultivar_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('safras_commodity_id_fkey'), 'cadastros_commodities', ['commodity_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('cultura',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('safra_tarefas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safra_tarefas_tipo'))
        batch_op.drop_index(batch_op.f('ix_safra_tarefas_talhao_id'))
        batch_op.drop_index(batch_op.f('ix_safra_tarefas_origem'))
        batch_op.drop_index(batch_op.f('ix_safra_tarefas_cultivo_area_id'))

    with op.batch_alter_table('romaneios_colheita', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_romaneios_colheita_cultivo_id'), 'cultivos', ['cultivo_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_romaneios_colheita_cultivo_id'))
        batch_op.alter_column('commodity_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Commodity colhida (derivada de safra.commodity_id, mas explícito para queries)',
               existing_nullable=True)

    with op.batch_alter_table('operacoes_agricolas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_operacoes_agricolas_cultivo_id'), 'cultivos', ['cultivo_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_operacoes_agricolas_tarefa_id'))
        batch_op.drop_index(batch_op.f('ix_operacoes_agricolas_cultivo_id'))

    with op.batch_alter_table('financeiro_comercializacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financeiro_comercializacoes_status'), ['status'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('receita_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID da Receita gerada no financeiro',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='RASCUNHO | CONFIRMADO | EM_TRANSITO | ENTREGUE | FINALIZADO | CANCELADO',
               existing_nullable=False,
               existing_server_default=sa.text("'RASCUNHO'::character varying"))
        batch_op.alter_column('nf_chave',
               existing_type=sa.VARCHAR(length=44),
               comment=None,
               existing_comment='Chave de acesso NF-e',
               existing_nullable=True)
        batch_op.alter_column('nf_numero',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Número da NF-e',
               existing_nullable=True)
        batch_op.alter_column('produto_colhido_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Lote de produto colhido vinculado (para rastreabilidade e baixa)',
               existing_nullable=True)
        batch_op.alter_column('frete_por_conta',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='COMPRADOR | VENDEDOR | CIF | FOB',
               existing_nullable=True)
        batch_op.alter_column('local_entrega',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Endereço/local de entrega',
               existing_nullable=True)
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='A_VISTA | PRAZO | BOLETO | PIX | TRANSFERENCIA',
               existing_nullable=True)
        batch_op.alter_column('valor_total',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='quantidade × preco_unitario',
               existing_nullable=False)
        batch_op.alter_column('preco_unitario',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment=None,
               existing_comment='Preço por unidade',
               existing_nullable=False)
        batch_op.alter_column('unidade',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Unidade de medida (herdada da commodity)',
               existing_nullable=False)
        batch_op.alter_column('quantidade',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               comment=None,
               existing_comment='Quantidade na unidade da commodity',
               existing_nullable=False)
        batch_op.alter_column('comprador_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Pessoa/empresa compradora',
               existing_nullable=False)
        batch_op.alter_column('numero_contrato',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Número do contrato / nota',
               existing_nullable=True)

    with op.batch_alter_table('fin_despesas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fin_despesas_cultivo_id'))
        batch_op.drop_column('cultivo_id')

    with op.batch_alter_table('cultivo_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cultivo_areas_area_id'))
        batch_op.create_index(batch_op.f('ix_cultivo_areas_analise_status'), ['tenant_id', 'analise_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cultivo_areas_analise_solo_id'), ['tenant_id', 'analise_solo_id'], unique=False)
        batch_op.alter_column('analise_status',
               existing_type=sa.VARCHAR(length=20),
               comment='NAO_SELECIONADA | SELECIONADA | REJEITADA',
               existing_nullable=False,
               existing_server_default=sa.text("'NAO_SELECIONADA'::character varying"))
        batch_op.alter_column('regiao_analise',
               existing_type=sa.VARCHAR(length=50),
               comment='Região para lookup de parâmetros: CERRADO | SUL | NORDESTE | SUDESTE | NORTE',
               existing_nullable=True)
        batch_op.alter_column('analise_solo_id',
               existing_type=sa.UUID(),
               comment='FK para analise selecionada para este talhão/cultivo',
               existing_nullable=True)

    with op.batch_alter_table('cafe_lotes_beneficiamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cafe_lotes_beneficiamento_cultivo_id'))
        batch_op.alter_column('cultivo_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Cultivo específico processado neste lote (rastreamento de produção por cultura)',
               existing_nullable=True)

    with op.batch_alter_table('cafe_lote_beneficiamento_romaneios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('cadastros_produtos_agricola', schema=None) as batch_op:
        batch_op.alter_column('principio_ativo',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    with op.batch_alter_table('cadastros_culturas', schema=None) as batch_op:
        batch_op.alter_column('v_meta_pct_padrao',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               comment='V% meta padrão para calagem desta cultura',
               existing_nullable=True)

    with op.batch_alter_table('cadastros_conversao_unidades', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('fator',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='destino = origem × fator',
               existing_nullable=False)

    with op.batch_alter_table('cadastros_commodities_cotacoes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('fonte',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Fonte da cotação: CEPEA, B3, CONAB, MANUAL',
               existing_nullable=True)
        batch_op.alter_column('preco',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               comment=None,
               existing_comment='Preço na unidade padrão da commodity',
               existing_nullable=False)

    with op.batch_alter_table('cadastros_commodities_classificacoes', schema=None) as batch_op:
        batch_op.alter_column('parametros_extras',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('desconto_impureza_por_ponto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Desconto % por ponto de impureza acima do máximo',
               existing_nullable=True)
        batch_op.alter_column('desconto_umidade_por_ponto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Desconto % por ponto de umidade acima do máximo',
               existing_nullable=True)
        batch_op.alter_column('classe',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='TIPO_1 | TIPO_2 | FORA_TIPO | ESPECIAL | PREMIUM',
               existing_nullable=False)

    with op.batch_alter_table('cadastros_commodities', schema=None) as batch_op:
        batch_op.alter_column('possui_cotacao',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('impureza_padrao_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Impureza padrão aceita sem desconto. Ex: 1.0',
               existing_nullable=True)
        batch_op.alter_column('umidade_padrao_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Umidade padrão MAPA para descontos. Ex: 14.0 para soja, 12.0 para café',
               existing_nullable=True)
        batch_op.alter_column('peso_unidade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Peso em kg da unidade padrão. Obrigatório para SACA_60KG, TONELADA, KG, ARROBA. Null para CABECA, LITRO, etc.',
               existing_nullable=True)
        batch_op.alter_column('sistema',
               existing_type=sa.BOOLEAN(),
               comment='True = não editável pelo tenant',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               comment='NULL = padrão do sistema',
               existing_nullable=True)

    with op.batch_alter_table('cadastros_areas_rurais', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_irrigacao_id')
        batch_op.drop_column('irrigado')
        batch_op.drop_column('tipo_solo_id')

    with op.batch_alter_table('analises_solo', schema=None) as batch_op:
        batch_op.alter_column('validade_meses',
               existing_type=sa.INTEGER(),
               comment='Meses de validade da análise',
               existing_nullable=True,
               existing_server_default=sa.text('12'))
        batch_op.alter_column('cultura_anterior',
               existing_type=sa.VARCHAR(length=100),
               comment='Cultura plantada anteriormente no talhão',
               existing_nullable=True)
        batch_op.alter_column('cultura_nome',
               existing_type=sa.VARCHAR(length=100),
               comment='Nome da cultura vinculada à análise',
               existing_nullable=True)
        batch_op.alter_column('sistema_manejo',
               existing_type=sa.VARCHAR(length=20),
               comment='PLANTIO_DIRETO | CONVENCIONAL | MINIMO',
               existing_nullable=True)
        batch_op.alter_column('tipo_irrigacao',
               existing_type=sa.VARCHAR(length=20),
               comment='SEQUEIRO | GOTEJAMENTO | PIVO_CENTRAL | ASPERSAO | SULCO',
               existing_nullable=True)
        batch_op.alter_column('manganes_mn',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               comment='mg/dm³',
               existing_nullable=True)
        batch_op.alter_column('ferro_fe',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               comment='mg/dm³',
               existing_nullable=True)
        batch_op.alter_column('boro_b',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               comment='mg/dm³',
               existing_nullable=True)
        batch_op.alter_column('zinco_zn',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               comment='mg/dm³',
               existing_nullable=True)
        batch_op.alter_column('saturacao_al_m_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='m% = Al / CTC × 100',
               existing_nullable=True)

    with op.batch_alter_table('agricola_produtos_colhidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultivo_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_agricola_produtos_colhidos_cultivo_id'), 'cultivos', ['cultivo_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_agricola_produtos_colhidos_status'), ['status'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='ARMAZENADO | RESERVADO | EM_TRANSITO | VENDIDO | PERDA',
               existing_nullable=False,
               existing_server_default=sa.text("'ARMAZENADO'::character varying"))
        batch_op.alter_column('nf_origem',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='NF de origem se veio de terceiro',
               existing_nullable=True)
        batch_op.alter_column('armazem_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Depósito/armazém onde está fisicamente',
               existing_nullable=True)
        batch_op.alter_column('destino',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='ARMAZEM | TERCEIRO | VENDIDO | TRANSITO',
               existing_nullable=True)
        batch_op.alter_column('peso_liquido_kg',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               comment=None,
               existing_comment='Peso líquido real em kg',
               existing_nullable=False)
        batch_op.alter_column('unidade',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Unidade de medida (herdada da commodity)',
               existing_nullable=False)
        batch_op.alter_column('quantidade',
               existing_type=sa.NUMERIC(precision=14, scale=3),
               comment=None,
               existing_comment='Quantidade na unidade da commodity',
               existing_nullable=False)
        batch_op.alter_column('classificacao_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Classificação de mercado atribuída (TIPO_1, PREMIUM, etc.)',
               existing_nullable=True)
        batch_op.alter_column('romaneio_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Romaneio de colheita que originou este lote (pode ser null se entrada manual)',
               existing_nullable=True)

    with op.batch_alter_table('agricola_orcamento_itens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agricola_orcamento_itens_cultivo_id'))
        batch_op.drop_column('cultivo_id')

    op.create_table('agricola_operacao_tipo_fase',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo_operacao', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment='Tipo de operação: PLANTIO, COLHEITA, PULVERIZAÇÃO, etc.'),
    sa.Column('fases_permitidas', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Lista de fases da safra permitidas: ["PLANTIO", "DESENVOLVIMENTO"]'),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True, comment='Descrição do tipo de operação'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('agricola_operacao_tipo_fase_pkey'))
    )
    with op.batch_alter_table('agricola_operacao_tipo_fase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agricola_operacao_tipo_fase_tipo_operacao'), ['tipo_operacao'], unique=True)

    with op.batch_alter_table('agricola_regras_agronomicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agricola_regras_agronomicas_tenant_id'))

    op.drop_table('agricola_regras_agronomicas')
    op.drop_table('cadastros_tipos_solo')
    op.drop_table('cadastros_tipos_irrigacao')
    # ### end Alembic commands ###
