"""produto_qtd_conteudo

Revision ID: f247473aa254
Revises: 5d3bfcf20877
Create Date: 2026-03-25 22:04:10.165817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f247473aa254'
down_revision: Union[str, Sequence[str], None] = '5d3bfcf20877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_conteudo', sa.Float(), nullable=True, comment='Quantidade de conteúdo por embalagem (ex: 3 para 3L/embalagem)'))
        batch_op.add_column(sa.Column('unidade_conteudo', sa.String(length=10), nullable=True, comment='Unidade do conteúdo (ex: L, KG, ML) quando diferente de unidade_medida'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_produtos', schema=None) as batch_op:
        batch_op.drop_column('unidade_conteudo')
        batch_op.drop_column('qtd_conteudo')

    # ### end Alembic commands ###
