"""refactor_plano_conta_add_hierarchy_rfb

Revision ID: f37b19542d58
Revises: a1aba30b643a
Create Date: 2026-03-22 22:40:21.049877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37b19542d58'
down_revision: Union[str, Sequence[str], None] = 'a1aba30b643a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fin_planos_conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Uuid(), nullable=True, comment='Conta pai (NULL = nível raiz)'))
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('natureza', sa.String(length=10), nullable=False, server_default='ANALITICA'))
        batch_op.add_column(sa.Column('categoria_rfb', sa.String(length=30), nullable=True, comment='Classificação RFB para Livro Caixa do Produtor Rural'))
        batch_op.add_column(sa.Column('ordem', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_sistema', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               comment='Ex: 3.01.02',
               existing_nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_fin_planos_conta_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_planos_conta_tipo'), ['tipo'], unique=False)
        batch_op.create_foreign_key(None, 'fin_planos_conta', ['parent_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fin_planos_conta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fin_planos_conta_tipo'))
        batch_op.drop_index(batch_op.f('ix_fin_planos_conta_parent_id'))
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('codigo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Ex: 3.01.02',
               existing_nullable=False)
        batch_op.drop_column('is_sistema')
        batch_op.drop_column('ordem')
        batch_op.drop_column('categoria_rfb')
        batch_op.drop_column('natureza')
        batch_op.drop_column('descricao')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
