"""add_cpf_telefone_to_usuarios

Revision ID: f58b4e673940
Revises: add_propriedade_exploracao_rural
Create Date: 2026-04-07 23:52:37.088677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f58b4e673940'
down_revision: Union[str, Sequence[str], None] = 'add_propriedade_exploracao_rural'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastros_documentos_exploracao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_documentos_exploracao_exploracao_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_documentos_exploracao_tenant_id'))

    op.drop_table('cadastros_documentos_exploracao')
    with op.batch_alter_table('cadastros_exploracoes_rurais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_exploracoes_rurais_fazenda_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_exploracoes_rurais_propriedade_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_exploracoes_rurais_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_exploracoes_tenant'))
        batch_op.drop_index(batch_op.f('ix_exploracoes_vigencia'))

    op.drop_table('cadastros_exploracoes_rurais')
    with op.batch_alter_table('cadastros_propriedades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_propriedades_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_propriedades_tenant'))

    op.drop_table('cadastros_propriedades')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=True, comment='CPF sem formatação — único na plataforma'))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_cpf'), ['cpf'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_cpf'))
        batch_op.drop_column('telefone')
        batch_op.drop_column('cpf')

    op.create_table('cadastros_propriedades',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('cpf_cnpj', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    sa.Column('inscricao_estadual', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ie_isento', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('nome_fantasia', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('regime_tributario', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('cor', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('icone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('cadastros_propriedades_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cadastros_propriedades_pkey'))
    )
    with op.batch_alter_table('cadastros_propriedades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_propriedades_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_propriedades_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cadastros_exploracoes_rurais',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('propriedade_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('natureza', sa.VARCHAR(length=30), server_default=sa.text("'propria'::character varying"), autoincrement=False, nullable=False),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('numero_contrato', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('valor_anual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentual_producao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('area_explorada_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('documento_s3_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('documento_tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], name=op.f('cadastros_exploracoes_rurais_fazenda_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['propriedade_id'], ['cadastros_propriedades.id'], name=op.f('cadastros_exploracoes_rurais_propriedade_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('cadastros_exploracoes_rurais_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cadastros_exploracoes_rurais_pkey'))
    )
    with op.batch_alter_table('cadastros_exploracoes_rurais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exploracoes_vigencia'), ['data_inicio', 'data_fim'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploracoes_tenant'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_exploracoes_rurais_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_exploracoes_rurais_propriedade_id'), ['propriedade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_exploracoes_rurais_fazenda_id'), ['fazenda_id'], unique=False)

    op.create_table('cadastros_documentos_exploracao',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exploracao_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nome_arquivo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('storage_backend', sa.VARCHAR(length=10), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False),
    sa.Column('tamanho_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_emissao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_validade', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('numero_documento', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('orgao_expedidor', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exploracao_id'], ['cadastros_exploracoes_rurais.id'], name=op.f('cadastros_documentos_exploracao_exploracao_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('cadastros_documentos_exploracao_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cadastros_documentos_exploracao_pkey'))
    )
    with op.batch_alter_table('cadastros_documentos_exploracao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_documentos_exploracao_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_documentos_exploracao_exploracao_id'), ['exploracao_id'], unique=False)

    # ### end Alembic commands ###
