"""onda1_cadastros_normalizacao

Revision ID: fa37f6f94792
Revises: c157f09d6817
Create Date: 2026-03-24 22:37:21.352917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa37f6f94792'
down_revision: Union[str, Sequence[str], None] = 'c157f09d6817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastros_pessoas_bancario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_conta', sa.String(length=20), nullable=False, comment='CORRENTE | POUPANCA | SALARIO | PIX'),
    sa.Column('banco_codigo', sa.String(length=10), nullable=True),
    sa.Column('banco_nome', sa.String(length=100), nullable=True),
    sa.Column('agencia', sa.String(length=10), nullable=True),
    sa.Column('conta', sa.String(length=20), nullable=True),
    sa.Column('chave_pix', sa.String(length=150), nullable=True),
    sa.Column('titular_nome', sa.String(length=200), nullable=True),
    sa.Column('titular_cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_pessoas_bancario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_bancario_pessoa_id'), ['pessoa_id'], unique=False)

    op.create_table('cadastros_pessoas_contatos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='CELULAR | TELEFONE | EMAIL | WHATSAPP | SITE | OUTRO'),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True, comment="Ex: 'Contato financeiro', 'WhatsApp pessoal'"),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_pessoas_contatos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_contatos_pessoa_id'), ['pessoa_id'], unique=False)

    op.create_table('cadastros_pessoas_documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='CPF | CNPJ | RG | IE | PASSAPORTE | CNH | OUTRO'),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('orgao_emissor', sa.String(length=50), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('razao_social', sa.String(length=200), nullable=True, comment='Apenas para CNPJ'),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True, comment='Apenas para CNPJ'),
    sa.Column('data_fundacao', sa.Date(), nullable=True, comment='Apenas para CNPJ'),
    sa.Column('nome_completo', sa.String(length=200), nullable=True, comment='Apenas para CPF'),
    sa.Column('data_nascimento', sa.Date(), nullable=True, comment='Apenas para CPF'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'tipo', name='uq_pessoa_documento_tipo')
    )
    with op.batch_alter_table('cadastros_pessoas_documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_documentos_pessoa_id'), ['pessoa_id'], unique=False)

    op.create_table('cadastros_areas_rurais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True, comment='Código interno (ex: T-01, P-01)'),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('area_hectares', sa.Float(), nullable=True, comment='Calculado do polígono ou preenchido manualmente'),
    sa.Column('area_hectares_manual', sa.Float(), nullable=True, comment='Override manual quando não há geometria'),
    sa.Column('geometria', sa.JSON(), nullable=True, comment='GeoJSON Polygon/MultiPolygon. Nulo para tipos administrativos.'),
    sa.Column('centroide_lat', sa.Float(), nullable=True),
    sa.Column('centroide_lng', sa.Float(), nullable=True),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['cadastros_areas_rurais.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_areas_rurais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_areas_rurais_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_areas_rurais_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_areas_rurais_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_areas_rurais_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_areas_rurais_tipo'), ['tipo'], unique=False)

    op.create_table('cadastros_equipamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('fazenda_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=True),
    sa.Column('ano_modelo', sa.Integer(), nullable=True),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('chassi', sa.String(length=50), nullable=True),
    sa.Column('numero_serie', sa.String(length=50), nullable=True),
    sa.Column('patrimonio', sa.String(length=50), nullable=True, comment='Número de patrimônio interno'),
    sa.Column('combustivel', sa.String(length=20), nullable=False),
    sa.Column('potencia_cv', sa.Float(), nullable=True),
    sa.Column('capacidade_tanque_l', sa.Float(), nullable=True),
    sa.Column('horimetro_atual', sa.Float(), nullable=False),
    sa.Column('km_atual', sa.Float(), nullable=False),
    sa.Column('valor_aquisicao', sa.Float(), nullable=True),
    sa.Column('data_aquisicao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_atual', sa.Float(), nullable=True, comment='Valor de mercado atual estimado'),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_equipamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_equipamentos_fazenda_id'), ['fazenda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_equipamentos_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_equipamentos_placa'), ['placa'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_equipamentos_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cadastros_equipamentos_tipo'), ['tipo'], unique=False)

    op.create_table('cadastros_areas_matriculas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('numero_matricula', sa.String(length=100), nullable=False),
    sa.Column('cartorio', sa.String(length=200), nullable=True),
    sa.Column('comarca', sa.String(length=100), nullable=True),
    sa.Column('area_matricula_ha', sa.Float(), nullable=True),
    sa.Column('car_numero', sa.String(length=100), nullable=True, comment='Cadastro Ambiental Rural'),
    sa.Column('nirf', sa.String(length=30), nullable=True, comment='Número do Imóvel na Receita Federal'),
    sa.Column('incra', sa.String(length=30), nullable=True, comment='Código INCRA do imóvel'),
    sa.Column('ccir', sa.String(length=30), nullable=True, comment='Certificado de Cadastro de Imóvel Rural'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['cadastros_areas_rurais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_areas_matriculas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_areas_matriculas_area_id'), ['area_id'], unique=False)

    op.create_table('cadastros_areas_registros_ambientais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_registro', sa.String(length=50), nullable=False, comment='CAR_APP | CAR_RL | LICENCA_IBAMA | AIA | OUTORGA_AGUA | OUTRO'),
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('orgao', sa.String(length=100), nullable=True),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('link_documento', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['cadastros_areas_rurais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadastros_areas_registros_ambientais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_areas_registros_ambientais_area_id'), ['area_id'], unique=False)

    # Dependentes devem ser dropados antes da tabela pai
    op.drop_table('imoveis_benfeitorias')
    op.drop_table('imoveis_matriculas')

    with op.batch_alter_table('imoveis_rurais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imoveis_rurais_car_numero'))
        batch_op.drop_index(batch_op.f('ix_imoveis_rurais_tenant_id'))

    op.drop_table('imoveis_rurais')

    # Remover FKs dependentes de frota_maquinarios antes de dropar a tabela
    with op.batch_alter_table('frota_ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipamento_id', sa.Uuid(), nullable=False))
        batch_op.alter_column('tipo', existing_type=sa.VARCHAR(length=30), comment='PREVENTIVA | CORRETIVA | REVISAO', existing_nullable=False)
        batch_op.alter_column('status', existing_type=sa.VARCHAR(length=20), comment='ABERTA | EM_EXECUCAO | CONCLUIDA | CANCELADA', existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_frota_ordens_servico_maquinario_id'))
        batch_op.create_index(batch_op.f('ix_frota_ordens_servico_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('frota_ordens_servico_maquinario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cadastros_equipamentos', ['equipamento_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('maquinario_id')

    with op.batch_alter_table('frota_planos_manutencao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipamento_id', sa.Uuid(), nullable=False))
        batch_op.create_index(batch_op.f('ix_frota_planos_manutencao_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('frota_planos_manutencao_maquinario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cadastros_equipamentos', ['equipamento_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('maquinario_id')

    with op.batch_alter_table('frota_registros_manutencao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipamento_id', sa.Uuid(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_frota_registros_manutencao_maquinario_id'))
        batch_op.create_index(batch_op.f('ix_frota_registros_manutencao_equipamento_id'), ['equipamento_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('frota_registros_manutencao_maquinario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cadastros_equipamentos', ['equipamento_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('maquinario_id')

    with op.batch_alter_table('frota_maquinarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frota_maquinarios_fazenda_id'))
        batch_op.drop_index(batch_op.f('ix_frota_maquinarios_tenant_id'))

    op.drop_table('frota_maquinarios')

    # Remover FKs dependentes de pessoas antes de dropar a tabela
    with op.batch_alter_table('fin_despesas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fin_despesas_pessoa_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cadastros_pessoas', ['pessoa_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fin_receitas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fin_receitas_pessoa_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cadastros_pessoas', ['pessoa_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoas_cpf_cnpj'))
        batch_op.drop_index(batch_op.f('ix_pessoas_nome'))
        batch_op.drop_index(batch_op.f('ix_pessoas_tenant_id'))

    op.drop_table('pessoas')
    with op.batch_alter_table('cadastros_pessoas_pii', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_pii_pessoa_id'))

    op.drop_table('cadastros_pessoas_pii')
    with op.batch_alter_table('cadastros_pessoas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('dados_extras', sa.JSON(), nullable=True, comment='Atributos customizados por tenant'))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=2),
               comment='PF | PJ',
               existing_nullable=False)

    with op.batch_alter_table('cadastros_pessoas_consentimentos', schema=None) as batch_op:
        batch_op.alter_column('finalidade',
               existing_type=sa.VARCHAR(length=50),
               comment='OPERACIONAL | MARKETING | ANALYTICS',
               existing_nullable=False)
        batch_op.alter_column('canal',
               existing_type=sa.VARCHAR(length=20),
               comment='WEB | APP | PRESENCIAL | IMPORTACAO',
               existing_nullable=False)

    with op.batch_alter_table('cadastros_pessoas_enderecos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal', sa.Boolean(), nullable=False))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               comment='PRINCIPAL | ENTREGA | COBRANCA | RURAL',
               existing_nullable=False)

    with op.batch_alter_table('cadastros_tipos_relacionamento', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               comment='NULL = padrão do sistema',
               existing_nullable=True)
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               comment='FORNECEDOR | CLIENTE | FUNCIONARIO | PRESTADOR | PARCEIRO | CONTADOR | OUTRO',
               existing_nullable=False)
        batch_op.alter_column('sistema',
               existing_type=sa.BOOLEAN(),
               comment='True = não editável pelo tenant',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frota_registros_manutencao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maquinario_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('frota_registros_manutencao_maquinario_id_fkey'), 'frota_maquinarios', ['maquinario_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_frota_registros_manutencao_equipamento_id'))
        batch_op.create_index(batch_op.f('ix_frota_registros_manutencao_maquinario_id'), ['maquinario_id'], unique=False)
        batch_op.drop_column('equipamento_id')

    with op.batch_alter_table('frota_planos_manutencao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maquinario_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('frota_planos_manutencao_maquinario_id_fkey'), 'frota_maquinarios', ['maquinario_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_frota_planos_manutencao_equipamento_id'))
        batch_op.drop_column('equipamento_id')

    with op.batch_alter_table('frota_ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maquinario_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('frota_ordens_servico_maquinario_id_fkey'), 'frota_maquinarios', ['maquinario_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_frota_ordens_servico_equipamento_id'))
        batch_op.create_index(batch_op.f('ix_frota_ordens_servico_maquinario_id'), ['maquinario_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='ABERTA | EM_EXECUCAO | CONCLUIDA | CANCELADA',
               existing_nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='PREVENTIVA | CORRETIVA | REVISAO',
               existing_nullable=False)
        batch_op.drop_column('equipamento_id')

    with op.batch_alter_table('fin_receitas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fin_receitas_pessoa_id_fkey'), 'pessoas', ['pessoa_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('fin_despesas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fin_despesas_pessoa_id_fkey'), 'pessoas', ['pessoa_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cadastros_tipos_relacionamento', schema=None) as batch_op:
        batch_op.alter_column('sistema',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True = não editável pelo tenant',
               existing_nullable=False)
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='FORNECEDOR | CLIENTE | FUNCIONARIO | PRESTADOR | PARCEIRO | CONTADOR | OUTRO',
               existing_nullable=False)
        batch_op.alter_column('tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL = padrão do sistema',
               existing_nullable=True)

    with op.batch_alter_table('cadastros_pessoas_enderecos', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='PRINCIPAL | ENTREGA | COBRANCA | RURAL',
               existing_nullable=False)
        batch_op.drop_column('principal')

    with op.batch_alter_table('cadastros_pessoas_consentimentos', schema=None) as batch_op:
        batch_op.alter_column('canal',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='WEB | APP | PRESENCIAL | IMPORTACAO',
               existing_nullable=False)
        batch_op.alter_column('finalidade',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='OPERACIONAL | MARKETING | ANALYTICS',
               existing_nullable=False)

    with op.batch_alter_table('cadastros_pessoas', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=2),
               comment=None,
               existing_comment='PF | PJ',
               existing_nullable=False)
        batch_op.drop_column('dados_extras')
        batch_op.drop_column('tags')
        batch_op.drop_column('observacoes')

    op.create_table('cadastros_pessoas_pii',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pessoa_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cpf', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('rg', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('razao_social', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('nome_fantasia', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ie', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('data_fundacao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('celular', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['cadastros_pessoas.id'], name=op.f('cadastros_pessoas_pii_pessoa_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cadastros_pessoas_pii_pkey'))
    )
    with op.batch_alter_table('cadastros_pessoas_pii', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadastros_pessoas_pii_pessoa_id'), ['pessoa_id'], unique=True)

    op.create_table('pessoas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo_principal', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='FORNECEDOR, CLIENTE, FUNCIONARIO, PARCEIRO, PRESTADOR, OUTRO'),
    sa.Column('tipos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment="Lista de todos os tipos aplicáveis (ex: ['FORNECEDOR', 'CLIENTE'])"),
    sa.Column('tipo_pessoa', sa.VARCHAR(length=2), autoincrement=False, nullable=False, comment='PF (pessoa física) ou PJ (pessoa jurídica)'),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('nome_fantasia', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cpf_cnpj', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    sa.Column('rg_ie', sa.VARCHAR(length=30), autoincrement=False, nullable=True, comment='RG (PF) ou Inscrição Estadual (PJ)'),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('celular', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('logradouro', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('numero', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('complemento', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('uf', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('banco_codigo', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('banco_agencia', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('banco_conta', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('banco_tipo_conta', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='CORRENTE, POUPANCA, PIX'),
    sa.Column('banco_chave_pix', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('pessoas_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pessoas_pkey'))
    )
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoas_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoas_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoas_cpf_cnpj'), ['cpf_cnpj'], unique=False)

    op.create_table('imoveis_matriculas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('imovel_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('numero_matricula', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cartorio', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('area_matricula_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis_rurais.id'], name=op.f('imoveis_matriculas_imovel_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('imoveis_matriculas_pkey'))
    )
    op.create_table('imoveis_benfeitorias',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('imovel_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('area_construida', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_estimado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis_rurais.id'], name=op.f('imoveis_benfeitorias_imovel_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('imoveis_benfeitorias_pkey'))
    )
    op.create_table('frota_maquinarios',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fazenda_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('marca', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ano', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('placa_chassi', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('horimetro_atual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('km_atual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('numero_serie', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('patrimonio', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('combustivel', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('potencia_cv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('capacidade_tanque_l', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], name=op.f('frota_maquinarios_fazenda_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('frota_maquinarios_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('frota_maquinarios_pkey'))
    )
    with op.batch_alter_table('frota_maquinarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frota_maquinarios_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frota_maquinarios_fazenda_id'), ['fazenda_id'], unique=False)

    op.create_table('imoveis_rurais',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('car_numero', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('nirf', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('incra', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('area_total_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('area_preservacao_ha', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('geometria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('imoveis_rurais_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('imoveis_rurais_pkey'))
    )
    with op.batch_alter_table('imoveis_rurais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imoveis_rurais_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imoveis_rurais_car_numero'), ['car_numero'], unique=False)

    with op.batch_alter_table('cadastros_areas_registros_ambientais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_areas_registros_ambientais_area_id'))

    op.drop_table('cadastros_areas_registros_ambientais')
    with op.batch_alter_table('cadastros_areas_matriculas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_areas_matriculas_area_id'))

    op.drop_table('cadastros_areas_matriculas')
    with op.batch_alter_table('cadastros_equipamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_equipamentos_tipo'))
        batch_op.drop_index(batch_op.f('ix_cadastros_equipamentos_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_equipamentos_placa'))
        batch_op.drop_index(batch_op.f('ix_cadastros_equipamentos_nome'))
        batch_op.drop_index(batch_op.f('ix_cadastros_equipamentos_fazenda_id'))

    op.drop_table('cadastros_equipamentos')
    with op.batch_alter_table('cadastros_areas_rurais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_areas_rurais_tipo'))
        batch_op.drop_index(batch_op.f('ix_cadastros_areas_rurais_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_areas_rurais_parent_id'))
        batch_op.drop_index(batch_op.f('ix_cadastros_areas_rurais_nome'))
        batch_op.drop_index(batch_op.f('ix_cadastros_areas_rurais_fazenda_id'))

    op.drop_table('cadastros_areas_rurais')
    with op.batch_alter_table('cadastros_pessoas_documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_documentos_pessoa_id'))

    op.drop_table('cadastros_pessoas_documentos')
    with op.batch_alter_table('cadastros_pessoas_contatos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_contatos_pessoa_id'))

    op.drop_table('cadastros_pessoas_contatos')
    with op.batch_alter_table('cadastros_pessoas_bancario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadastros_pessoas_bancario_pessoa_id'))

    op.drop_table('cadastros_pessoas_bancario')
    # ### end Alembic commands ###
